### ISSUE TITLE
iOS Scanner v4.0.4 ignores statusBar enabled false

### ISSUE THREAD

**Issue by satusuuronen** [AppGyver/steroids#1009]
When the statusBar is disabled in the app.config:
```
statusBar:
enabled: false
```
the status bar displayed in the app.

**Comment by owenhoskins** [comment]
+1

**Comment by harsaharsa** [comment]
Will be fixed in 4.0.5 (available in Build Service soon)!

**Comment by owenhoskins** [comment]
This seems to be fixed for AdHoc and Scanner builds, great!

But my ios emulator is still sporting the status bar! Is there an update for this?

**Comment by satusuuronen** [comment]
The iOS simulator will be updated when 4.0.5 is released as the Stable AppGyver iOS Native Runtime.
