### ISSUE TITLE
Build service using Crosswalk even with Platform Webview mode selected

### ISSUE THREAD

**Issue by fabriciomassula** [AppGyver/steroids#1014]
Hello,

Starting from 4.0.6 (Android), the build service is building the APK with the Crosswalk, even with the Platform Webview mode selected.

This user reported some related issue:
http://community.appgyver.com/t/android-build-size-increased-in-400-since-4-0-6-edge-in-steroids/2750

I need the bugfixes of 4.0.6 to launch my app, by I want to launch it with the Webview.

**Comment by fabriciomassula** [comment]
My apk on build 4.0.5 is 4MB, and with 4.0.6 is 40MB!

**Comment by satusuuronen** [comment]
This issue has already been reported. I am closing this issue and keeping [#954](https://github.com/AppGyver/steroids/issues/954] open.
