### ISSUE TITLE
Push notifiation badge count 

### ISSUE THREAD

**Issue by mitiaptest** [AppGyver/steroids#1015]
setApplicationIconBadgeNumber only clear the badge count on icon i need to  mange it i.e increment and decrement .Is this issue or this is not functionality on appgyrver plug in ?

**Comment by g-liu** [comment]
I believe you are referring to the Pushwoosh plugin? See https://rawgit.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/master/Documentation/files/PushNotification-js.html

**Comment by satusuuronen** [comment]
Which push plugin are you using?

**Comment by mitiaptest** [comment]
Issue resolved, 
Thanks
