### ISSUE TITLE
Reference to deprecated link on ../configuring-custom-plugins

### ISSUE THREAD

**Issue by marcussaad** [AppGyver/steroids#1026]
This link is broken and can be found at http://docs.appgyver.com/tooling/build-service/plugins/configuring-custom-plugins/

Link should point to http://docs.appgyver.com/tooling/build-service/plugins/default-plugins/

![screenshot-docs appgyver com 2015-08-21 00-05-23](https://cloud.githubusercontent.com/assets/1544280/9400511/63a55b5c-4798-11e5-8b52-4275c309fda1.png)

**Comment by satusuuronen** [comment]
Thanks for reporting! It's fixed now.
