### ISSUE TITLE
Supersonic Data Channel Duplicates

### ISSUE THREAD

**Issue by thedeukalion** [AppGyver/steroids#1039]
In our project we use the:

supersonic.data.channel('channel').subscribe() and
supersonic.data.channel('channel').publish() alot for communication between views.

Now with the latest update to supersonic 1.7.6 all "publish" calls the method or twice:

```
supersonic.data.channel('test').subscribe(function()
{
    console.log("Test got called");
});
supersonic.data.channel('test').publish();
```

And the log says:

```
(2) Test got called
```

Not sure how long ago this occured, but I updated from 1.5.* some version to 1.7.6 and this has started to occur now.

This kind of screws up alot of methods since we use it for communicating with servers. We have one global object that registers all "subscriptions" ONCE (checked so it only does this once).

Doesn't matter which view I put it in (only add this test in one view per time) it gets called twice either way. Sometimes, it has been called alot of times (think due to livereload?).

**Comment by thedeukalion** [comment]
Investigated further and it seems not to be relative to the supersonic component but rather the Steroids update. Maybe a move if possible. Gonna look through the code. But, changing from Steroids version 3.5.14 to 3.5.12 makes this disappear.

**Comment by satusuuronen** [comment]
Thanks for the report. Most likely related to [this issue](https://github.com/AppGyver/steroids/issues/1033).

**Comment by sunny061** [comment]
How do I downgrade steroids so I can get the pubsub to stop publishing twice?

**Comment by thedeukalion** [comment]
I downgraded from 3.5.14 and 3.5.15 to 3.5.12. I searched as well, but had it in my gitrep so I copied an earlier version. In case you can't find it: http://s000.tinyupload.com/index.php?file_id=23582669098752936651

**Comment by sunny061** [comment]
@thedeukalion Thanks

**Comment by ezramorse** [comment]
I use message IDs with the source and a timestamp when emitting, which I record by all subs and only execute once (put them in an array and use indexOf).

Interestingly, I don't experience his in any webviews except the one emitting the event (if its also a subscriber)

**Comment by pre** [comment]
There's a known issue currently that the sending WebView will get the message twice.

**Comment by sunny061** [comment]
@pre This issue has been around for quite some time now. Any updates on when a fix is coming?

**Comment by harsaharsa** [comment]
This should now be fixed with Steroids.js 3.5.18 onwards. Please reply here if issues still occur.
