### ISSUE TITLE
Steroids.view.updateKeyboard not working

### ISSUE THREAD

**Issue by highvoltag3** [AppGyver/steroids#1040]
It seems like steroids.view.updateKeyboard is not working following the documentation

```
steroids.view.updateKeyboard({
  accessoryBarEnabled: false
}, {
  onSuccess: function() {
    alert("Keyboard accessory bar disabled for this view!");
  },
  onFailure: function() {
    alert("Could not update keyboard!")
  }
});
```
Does nothing :frowning: anyone bumped into this?

**Comment by pre** [comment]
We will need to update docs on that part. Ionic Keyboard plugin was removed from list the default plugins in summer 2015. 

You can include it manually using https://github.com/driftyco/ionic-plugin-keyboard and creating a custom build from the Build Service (cloud.appgyver.com). Then the code above should work again.
