### ISSUE TITLE
XCode 7 and Steroids, can't launch simulator..

### ISSUE THREAD

**Issue by highvoltag3** [AppGyver/steroids#1041]
Getting the following after installing the XCode 7 update that Apple has release to the public on the Apple Store.

```
AppGyver Steroids command  
  __________________  ___________
_/ __ \_  __ \_  __ \/  _ \_  __ \
\  ___/|  | \/|  | \(  <_> )  | \/
 \___  >__|   |__|   \____/|__|
     \/


Please update to XCode 6 to run the simulator.
```

Seems like there's an open PR #1037  for this from the awesome @leeds-ebooks

**Comment by satusuuronen** [comment]
Fixed in CLI v 4.1.19.
