### ISSUE TITLE
iOS 9 supersonic.ui.dialog.prompt() visual bug

### ISSUE THREAD

**Issue by Leeds-eBooks** [AppGyver/steroids#1042]
No explanation needed! (Simulator version is in the screenshot header bar, this also appears on other device simulators eg iPhone 6s Plus)

<img width="432" alt="screen shot 2015-09-17 at 16 00 25" src="https://cloud.githubusercontent.com/assets/4380655/9936747/739be800-5d55-11e5-86dc-d42257e3d905.png">

**Comment by pentateu** [comment]
have you tested on a device ? same issue?

**Comment by Leeds-eBooks** [comment]
Yep this is on a real iPad:

![file 18-09-2015 11 34 16](https://cloud.githubusercontent.com/assets/4380655/9957606/3e15ef92-5df9-11e5-958b-fb7b18df9aff.png)

**Comment by justincolangelo** [comment]
Same issue here on device.

**Comment by highvoltag3** [comment]
+1 iPad, iPhone

**Comment by mitiaptest** [comment]
+1 same issue

**Comment by wiwat-tharateeraparb** [comment]
+1

**Comment by mitiaptest** [comment]
Any update ?

**Comment by wiwat-tharateeraparb** [comment]
Tested with 4.1.21 and it still has this bug.

**Comment by wiwat-tharateeraparb** [comment]
Just wondering if there is an alternative for `supersonic.ui.dialog.prompt()` while we're waiting for the fix?

**Comment by wiwat-tharateeraparb** [comment]
Same if call `navigator.notification.prompt()`

**Comment by wiwat-tharateeraparb** [comment]
Tested with iOS 9.1. Issue still persists.

**Comment by wiwat-tharateeraparb** [comment]
Hi, is there any update on this?

**Comment by wiwat-tharateeraparb** [comment]
Also notice that with `prompt()` and software keyboard present, it forces my CSS media query to be in `landscape` even the device is in `portrait` orientation.

**Comment by harsaharsa** [comment]
I'll get an update on this from the iOS team, thanks for keeping this bumped!

**Comment by wiwat-tharateeraparb** [comment]
Hi, is there an update from iOS team somehow?

**Comment by wiwat-tharateeraparb** [comment]
@harsaharsa do you know if this is going to be fixed in near future?

**Comment by netolicak** [comment]
+1, iPad, iPhone, iPod

**Comment by wiwat-tharateeraparb** [comment]
Any news on this?

**Comment by Leeds-eBooks** [comment]
@harsaharsa bump! This must be a quick fix?

**Comment by harsaharsa** [comment]
Probably – though it's a Cordova component, so it might be a deep rabbit hole that opens up. There's unfortunately a lot of other important issues (as, of course, there always is), and with Composer 2 in the revenue focus, this keeps getting pushed back in the backlog.

If you want to investigate this yourself, it's possible – we're using https://github.com/AppGyver/cordova-plugin-dialogs in all of the builds hard-coded, so you can't just swap out the plugin in the Build Service.

However, you could try forking that plugin, rebasing our modifications on top of the current Cordova master commit and then manually switching the namespace (i.e. renaming files and methods) so it will install via the Build Service alongside the current plugin, and the see if the improved plugin fixes the bug. It's a very convoluted way to contribute, but it's something to try. Sorry that I can't be of more help!

**Comment by Leeds-eBooks** [comment]
@harsaharsa Would a pull request to https://github.com/AppGyver/cordova-plugin-dialogs work?

**Comment by wiwat-tharateeraparb** [comment]
If I put below configuration in build service under Plugins:
```
[
  {"source":"https://github.com/apache/cordova-plugin-dialogs.git"}
]
```
Would it ovrerride the default plugin?

**Comment by Leeds-eBooks** [comment]
I think that's what @harsaharsa meant by
> we're using https://github.com/AppGyver/cordova-plugin-dialogs in all of the builds hard-coded, so you can't just swap out the plugin in the Build Service.

So no, I don't think you can just use a different plugin.

**Comment by juhazi** [comment]
Although it is not supported to override our default plugins, you can still use your own version of them.

To use your own fork of a default plugin requires three steps:

1. fork the plugin version you want to override with( e.g. from above https://github.com/apache/cordova-plugin-dialogs ) so you can make changes.
1. select a different plugin ID (for dialogs its here https://github.com/AppGyver/cordova-plugin-dialogs/blob/master/plugin.xml#L22 )
1. update the javascript interface to not conflict with the original plugin(for dialogs this https://github.com/AppGyver/cordova-plugin-dialogs/blob/master/plugin.xml#L33 must be changed)

Updating the javascript interface might require different changes for some other plugins.

Also note that changing the javascript interface from e.g. navigator.notification to navigator.betterNotification requires a change in the app code as well.

**Comment by wiwat-tharateeraparb** [comment]
Thanks. How do we test custom plugin locally on iOS simulator then?

**Comment by ukrit-himakoon** [comment]
Hello @juhazi,

I have tried the recommended method following step 1,2 and 3 as suggested. Unfortunately, after using the build service we experience the error below reported.
    
    Adding plugin from: https://github.com/ukrit-himakoon/cordova-plugin-dialogs.git
    Uh oh!
    target destination "/Users/administrator/app-builder/STAGING/client/Resources/CDVNotification.bundle" already exists

One more question, Is it the way to upgrade cordova locally and make it able to be tested using iOSsimulator like wiwat mentioned above?

**Comment by pre** [comment]
While you can't upgrade Cordova without access to the native code, you can request a custom simulator build from the Build Service.

**Comment by ukrit-himakoon** [comment]
However, is there any confirmed schedule when this issue will be officially fixed?

**Comment by ukrit-himakoon** [comment]
Hello @pre,
I need a build service which include ordova-plugin-dialogs-1.2.1 to the build service. How can we make a request for this?

Thank you so much,

**Comment by pre** [comment]
Unfortunately it's an unsupported configuration at the moment. Your can include it yourself following Juha's instructions, but you are on your own. Sorry.

**Comment by kaskew** [comment]
=[. More broken features with no plans to fix.

**Comment by wiwat-tharateeraparb** [comment]
http://stackoverflow.com/questions/32721782/uialertcontroller-textfield-width-is-way-smaller-than-usual

http://stackoverflow.com/questions/32762287/uialertcontroller-not-working-in-ios-9/33434715

**Comment by kaskew** [comment]
Thanks for dropping those!

**Comment by wiwat-tharateeraparb** [comment]
We got a workaround by adding below CSS to native style file `native-styles/ios.css` and it works on iOS 9 now.

```
collection-view collection-view-cell > view {
  width: 270px;
}
```

As Steroids is using PixateFreestyle for native iOS styling, Pixate team has already fixed it (https://github.com/StylingKit/StylingKit/pull/38) but I guess it is not reflected in the latest Steroids run-time.

**Comment by Leeds-eBooks** [comment]
@wiwat-tharateeraparb Nice!! Great work.

**Comment by wiwat-tharateeraparb** [comment]
The issue reappears with iOS 10 even the workaround is applied. Scratch head....

**Comment by wiwat-tharateeraparb** [comment]
This visual bug still happens in iOS 10.2. To fixed this, Steroids needs to stop styling UIAlertView.
