### ISSUE TITLE
After El Capitan update the iOS Simulator fails to load the app

### ISSUE THREAD

**Issue by highvoltag3** [AppGyver/steroids#1050]
AppGyver scanner lunches and just shows an alert saying Connection Error, Could not open connection... (see attachment)

Ran `Steroids Update` and `npm update` same behavior.

![screen shot 2015-10-02 at 3 14 05 pm](https://cloud.githubusercontent.com/assets/694585/10258998/52b4084c-6918-11e5-829b-a1e369a12aaa.png)

**Comment by iDay** [comment]
+1

**Comment by harsaharsa** [comment]
Thanks, we'll investigate!

**Comment by nicholascc** [comment]
I have this problem too. I think it's because the Xcode Command-Line Tools are not ready for mac 10.11 yet.

**Comment by harsaharsa** [comment]
Confirmed on our end too, we'll try to work a solution ASAP. Sorry for the trouble!

**Comment by maroselo** [comment]
+1

**Comment by usenkanov** [comment]
+1

**Comment by harsaharsa** [comment]
We found out the problem – Simulator tries to connect to http://machine_ip:4567, which no longer works in El Capitan. Solution is to roll out a new version of Simulator that connects to http://localhost:4567. Stay tuned for updates!

**Comment by jublo** [comment]
:+1:

**Comment by jublo** [comment]
@harsaharsa How long until you have a working fix? This is a blocker for us.

**Comment by jublo** [comment]
Seeing a pending `4.1.21` release, waiting for the Travis builds. Mac is already showing up green.

https://travis-ci.org/AppGyver/steroids/builds/85137716

**Comment by jublo** [comment]
`4.1.21` is released now. Update using `npm install -g steroids`.

**Comment by jublo** [comment]
Fix works! Confirmed.

**Comment by usenkanov** [comment]
Thanks!!!

**Comment by pre** [comment]
gr8!

**Comment by sgarbesi** [comment]
Still not working for me.

AppGyver Steroids² 4.1.22

**Comment by samuelblattner** [comment]
I still have this issue with my custom build of the scanner. Has the code been updated there already? If I launch my app with the default scanner it works, though.

**Comment by pre** [comment]
Custom simulator builds do not have this fix... sorry about that. Build using "4.0.7 simulator" , it's available on the bottom of "Show older versions" .

**Comment by samuelblattner** [comment]
Many thanks @pre, that solved the problem :-)
