### ISSUE TITLE
Steroids 4.1.20 Connection Error on iOS 9 Simulator

### ISSUE THREAD

**Issue by wiwat-tharateeraparb** [AppGyver/steroids#1056]
<img width="229" alt="screen shot 2015-10-13 at 7 51 52 pm" src="https://cloud.githubusercontent.com/assets/3415706/10455185/08e63c4c-71e4-11e5-8638-17c2560cc857.png">

**Comment by jublo** [comment]
Duplicate of #1050.

**Comment by wiwat-tharateeraparb** [comment]
Solved with 4.1.21 update.
