### ISSUE TITLE
NAVBAR ICONS

### ISSUE THREAD

**Issue by mkwsra** [AppGyver/steroids#1060]
Dear development department/team,

I've wasted 3 hrs surfing the internet and reading in your Docs and here along with stackoverflow. I hope you take this issue as importnant thing to complete your amazing work and not waste it all since all developers are just quiting using your work.

Is if that Supersonic in Alfa? or you are just avoiding writing clear docs?

Please answer what tens of people are wondering in your community, and I'm one of them.

How to display svg icon in navbar? Css selectors aren't working other solutions like adding adding the selector icon after my selector didn't work... along with others.

giving svg icon for this selector well work, but for sure both buttons will be the same:
`navigation-bar button {....}`
but below one won't work on both platforms:
`navigation-bar button#hamburger {....}`

**Comment by mkwsra** [comment]
The last 5 issues (including mine) are open with no comment :-1: 

I loved you work, please let's do something about it!

**Comment by Sampax** [comment]
I agree that the documentation is not optimal, and we are truly sorry for the frustration it causes. As stated [here](http://community.appgyver.com/t/appgyver-community-dead-support-chat/5521), improving the developer experience is still one of our main concerns and will be addressed as soon as possible.

Regarding your specific issue, it should be covered [in the docs](http://docs.appgyver.com/supersonic/guides/ui/styling-native-components/navigation-bar-styling-example/#styling-icon-buttons). At the time of writing, you do have to use different styling for both platforms.

**Comment by mkwsra** [comment]
@Sampax Appreciate your response, wishing this project a rise
