### ISSUE TITLE
Uncaught TypeError: Failed to execute 'initCustomEvent' on 'CustomEvent': 4 arguments required, but only 3 present.

### ISSUE THREAD

**Issue by sunny061** [AppGyver/steroids#1065]
I am getting this error in steroids.js line 631

Uncaught TypeError: Failed to execute 'initCustomEvent' on 'CustomEvent': 4 arguments required, but only 3 present.

I am using a scanner built for platform webview on Android 5.0.2.

**Comment by harsaharsa** [comment]
Can you give more details about the situation? Does that happen with the default project, or are you running some of your own code? Does it happen at page load or some other point?

**Comment by poppahorse** [comment]
+1, it happens when you switch between tabs

`steroids.js:631 Uncaught TypeError: Failed to execute 'initCustomEvent' on 'CustomEvent': 4 arguments required, but only 3 present.`

**Comment by sunny061** [comment]
@harsaharsa It happens when I push a preloaded view and I am using the default code.

**Comment by ezramorse** [comment]
Change line 631 of steroids.js from:

visibilityChangeCustomEvent.initCustomEvent("visibilitychange", true, true);

to

visibilityChangeCustomEvent.initCustomEvent("visibilitychange", true, true, {});

**Comment by pre** [comment]
Thanks for the fix! This is now fixed in steroids-js 3.5.17.

It seems to only affect Android Platform WebView. There wasn't a problem with Crosswalk or iOS builds.
