### ISSUE TITLE
On an Android phone with 64bit architecture, Scanner crashes instantly when trying to scan the QR code

### ISSUE THREAD

**Issue by poppahorse** [AppGyver/steroids#1068]
This happens as soon as I press the (+), the camera doesn't initialise at all. Its on latest build 4.1.0. I have tried requesting a rebuild, but that has the same issue (interestingly it took over 30 mins to build, 99825 if that helps).

Oddly enough this was working fine this morning. all I can think thats changes is that I installed an adhoc version, which I have since uninstalled

I have tried rolling back to a 4.0.7-edge1 build which is allowing me to work for now, but not ideal.

output of `adb logcat`

```
11-03 13:38:50.987  4963  7043 D NetlinkSocketObserver: NeighborEvent{elapsedMs=3439938, 192.168.0.18, [AC220BD49F60], RTM_NEWNEIGH, NUD_STALE}
11-03 13:38:51.400 13452 13452 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 5
11-03 13:38:51.780  4963  7446 I ActivityManager: START u0 {cmp=com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity} from uid 10081 on display 0
11-03 13:38:51.807 13532 13532 D AndroidRuntime: Shutting down VM
11-03 13:38:51.808 13532 13532 E AndroidRuntime: FATAL EXCEPTION: main
11-03 13:38:51.808 13532 13532 E AndroidRuntime: Process: com.melonwebdesign.milehi.scanner, PID: 13532
11-03 13:38:51.808 13532 13532 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.melonwebdesign.milehi.scanner-1/base.apk"],nativeLibraryDirectories=[/data/app/com.melonwebdesign.milehi.scanner-1/lib/arm64, /data/app/com.melonwebdesign.milehi.scanner-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libiconv.so"
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at com.appgyver.scanner.ImageScannerActivity.<clinit>(ImageScannerActivity.java:65)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-03 13:38:51.808 13532 13532 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-03 13:38:51.809  4963  6642 W ActivityManager:   Force finishing activity com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity
11-03 13:38:51.814  4963  6642 W ActivityManager:   Force finishing activity com.melonwebdesign.milehi.scanner/com.appgyver.runtime.scanner.MainActivity
11-03 13:38:51.856  4963 12522 I OpenGLRenderer: Initialized EGL, version 1.4
11-03 13:38:52.315  4963  4991 W ActivityManager: Activity pause timeout for ActivityRecord{1cfa8b1 u0 com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity t279 f}
11-03 13:38:54.148  7736  9251 W ctxmgr  : [PowerConnectionState]Got same value as before for power connection (Plug state: 2 BatteryLevel: 0.96)

```

**Comment by andybbtt11** [comment]
My scanner app crashes instantly upon opening it, every time.  5.1.1 on Samsung S6 and S6+

**Comment by poppahorse** [comment]
Yeah the scanner can be a POS sometimes, I have gotten fairly used to random crashes here and there, but there definitely seem to be some odd persistent issues.

FYI I am on Android 6.0, have rebooted, uninstalled and reinstalled the app, etc.

**Comment by andybbtt11** [comment]
I tried building the current 4.1.0 scanner in webplatform view and it crashes as soon as I hit the +  button.  Same thing happens with 4.0.6 build in webplatform.  Gonna just keep going down the versions until one works.

**Comment by poppahorse** [comment]
4.0.7-edge1 was working for me if that helps, should be the one below 4.1.0

**Comment by andybbtt11** [comment]
Strange, for me it's 4.1.0 - > 4.0.6.

![screen shot 2015-11-03 at 11 02 16 am](https://cloud.githubusercontent.com/assets/1443791/10915012/7f8bd73a-821a-11e5-9784-2d6e797e9aac.png)

**Comment by poppahorse** [comment]
confirmed. well it WAS there, they must have removed it :(

**Comment by harsaharsa** [comment]
The 4.0.7-edge1 version was removed since we jumped straight to 4.1.0, and the edge version was "rolled into" 4.1.0.

I've now re-enabled it as we're investigating this, haven't been able to reproduce it yet on our end. Will deleting the app and it's data and then reinstalling help?

**Comment by poppahorse** [comment]
@harsaharsa thanks for the response, that was the first thing I tried :( Do you mean delete data first then uninstall, or should uninstall do that anyways?

**Comment by harsaharsa** [comment]
I'm not 100% how Android works; I'd imagine no cache remains, but you can try cleaning app data from the settings before deleting.

If anyone else has ADB LogCat logs of the crashes, that'd be very helpful!

**Comment by harsaharsa** [comment]
@poppahorse what device and Android OS version are you using?

**Comment by poppahorse** [comment]
Nexus 6P - Android 6.0. As mentioned, it was working fine for a while, then just started acting up (I think after I installed an adhoc version alongside).

**Comment by harsaharsa** [comment]
@poppahorse does the LogCat output stay the same? You are using the Scanner from Google Play when getting the error, right?

**Comment by harsaharsa** [comment]
@andybbtt11 would it be possible to get a logcat output for us?

For reference, here's another crash log from [this forum thread](http://community.appgyver.com/t/scanner-not-starting-anymore-on-my-android-5-0/5596/2): http://pastebin.ca/3234631

**Comment by poppahorse** [comment]
I will post another logcat shortly. I was using a custom build scanner actually (for facebook and push plugins), will give the play store one a try too.

**Comment by andybbtt11** [comment]
I wasn't exactly sure what to look for but I saw this in the logcat for the playstore version of scanner on my s6+ with 5.1.1:

E/AndroidRuntime(32381): FATAL EXCEPTION: main
E/AndroidRuntime(32381): Process: com.appgyver.freshandroid, PID: 32381
E/AndroidRuntime(32381): junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
E/AndroidRuntime(32381): 	at junit.framework.Assert.fail(Assert.java:50)
E/AndroidRuntime(32381): 	at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:180)
E/AndroidRuntime(32381): 	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:105)
E/AndroidRuntime(32381): 	at com.appgyver.webview.XWalkRuntimeConfig.<init>(XWalkRuntimeConfig.java:22)
E/AndroidRuntime(32381): 	at com.appgyver.runtime.scanner.chromium.ScannerChromiumApplication.onCreate(ScannerChromiumApplication.java:16)
E/AndroidRuntime(32381): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
E/AndroidRuntime(32381): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5932)
E/AndroidRuntime(32381): 	at android.app.ActivityThread.access$1700(ActivityThread.java:198)
E/AndroidRuntime(32381): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
E/AndroidRuntime(32381): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32381): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(32381): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
E/AndroidRuntime(32381): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32381): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32381): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(32381): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
V/ApplicationPolicy( 3535): isApplicationStateBlocked userId 0 pkgname com.appgyver.freshandroid
W/ActivityManager( 3535):   Force finishing activity 1 com.appgyver.freshandroid/com.appgyver.runtime.scanner.chromium.MainActivity

**Comment by pre** [comment]
Thanks for the report. The issue is that Samsung S6 is 64bit and the version of Crosswalk we have doesn't play well with 64bit cpu arch. We're working on a fix, it might be that we'll need to update to the beta Crosswalk version.

**Comment by andybbtt11** [comment]
Cool, I will make due with other phones in the time being. Thanks for the info @pre

**Comment by harsaharsa** [comment]
I changed the title to better reflect the actual issue, will keep this thread updated!

**Comment by poppahorse** [comment]
Ah yes, 64 bit would make sense being on the 6P. Although unsure how or why it was working in the first place.

Anyways here is another logcat if it helps:

```
11-09 09:56:10.943 31429 31429 I ServiceManager: Waiting for service AtCmdFwd...
11-09 09:56:11.944 31429 31429 I ServiceManager: Waiting for service AtCmdFwd...
11-09 09:56:12.317  4963 24855 I ActivityManager: START u0 {cmp=com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity} from uid 10081 on display 0
11-09 09:56:12.356 31169 31169 D AndroidRuntime: Shutting down VM
11-09 09:56:12.366 31169 31169 E AndroidRuntime: FATAL EXCEPTION: main
11-09 09:56:12.366 31169 31169 E AndroidRuntime: Process: com.melonwebdesign.milehi.scanner, PID: 31169
11-09 09:56:12.366 31169 31169 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.melonwebdesign.milehi.scanner-2/base.apk"],nativeLibraryDirectories=[/data/app/com.melonwebdesign.milehi.scanner-2/lib/arm64, /data/app/com.melonwebdesign.milehi.scanner-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libiconv.so"
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at com.appgyver.scanner.ImageScannerActivity.<clinit>(ImageScannerActivity.java:65)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-09 09:56:12.366 31169 31169 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-09 09:56:12.369  4963  6749 W ActivityManager:   Force finishing activity com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity
11-09 09:56:12.374  4963  6749 W ActivityManager:   Force finishing activity com.melonwebdesign.milehi.scanner/com.appgyver.runtime.scanner.MainActivity
11-09 09:56:12.424  4963 12522 I OpenGLRenderer: Initialized EGL, version 1.4
11-09 09:56:12.875  4963  4991 W ActivityManager: Activity pause timeout for ActivityRecord{468eac9 u0 com.melonwebdesign.milehi.scanner/com.appgyver.scanner.ImageScannerActivity t466 f}
11-09 09:56:12.944 31429 31429 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 4
11-09 09:56:13.008  4963  7448 I ActivityManager: Killing 30753:com.android.keychain/1000 (adj 15): empty #17
11-09 09:56:13.508  7350  7585 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-09 09:56:18.194  4754 29394 D ClClient: D	2015-11-09T09:56:18.194+0000	[ci=k4oNWmJPuD]	pool-6-thread-1  	ClClient       	Not sending keepalive.  Current connection state=STOPPED
11-09 09:56:21.101 31169 31169 I Process : Sending signal. PID: 31169 SIG: 9
11-09 09:56:21.123  7176  7176 I Keyboard.Facilitator: onFinishInput()
11-09 09:56:21.207  4963  6642 I WindowState: WIN DEATH: Window{a3e17ee u0 com.melonwebdesign.milehi.scanner/com.appgyver.runtime.scanner.MainActivity}
11-09 09:56:21.207  4963 22320 D GraphicsStats: Buffer count: 15
11-09 09:56:21.225 22720 31876 I MicroRecognitionRnrImpl: Starting detection.
11-09 09:56:21.226 22720 31877 I MicrophoneInputStream: mic_starting com.google.android.apps.gsa.speech.audio.y@a002733
11-09 09:56:21.228  3720 31879 I AudioFlinger: AudioFlinger's thread 0xf2e40000 ready to run
11-09 09:56:21.233  3720  6301 I SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const android::sp<android::SoundTriggerHwService::CallbackEvent>&) mClient == 0
11-09 09:56:21.235 22720 31877 I MicrophoneInputStream: mic_started com.google.android.apps.gsa.speech.audio.y@a002733
11-09 09:56:21.244  4963  6749 I ActivityManager: Process com.melonwebdesign.milehi.scanner (pid 31169) has died
11-09 09:56:21.245  3720 31879 D audio_hw_primary: select_devices: out_snd_device(0: none) in_snd_device(61: voice-rec-mic)
11-09 09:56:21.245  3720 31879 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(61) acdb_id(62)
11-09 09:56:21.245  3720 31879 I ACDB-LOADER: ACDB AFE returned = -19
11-09 09:56:21.245  3720 31879 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x3d of type 1 for Event 1
11-09 09:56:21.245  3720 31879 D sound_trigger_platform: platform_stdev_check_and_update_concurrency: concurrency active 0, tx 1, rx 0, concurrency session_allowed 0
11-09 09:56:21.245  3720 31879 D audio_hw_primary: enable_snd_device: snd_device(61: voice-rec-mic)
11-09 09:56:21.251  3720 31879 D audio_hw_primary: enable_audio_route: apply and update mixer path: audio-record
11-09 09:56:21.272 28002 28101 I Icing   : Usage reports 1 indexed 0 rejected 0 imm upload true
11-09 09:56:21.278  4963  4972 I art     : Background partial concurrent mark sweep GC freed 77713(4MB) AllocSpace objects, 18(376KB) LOS objects, 27% free, 42MB/58MB, paused 1.063ms total 144.452ms
11-09 09:56:21.287  4963  5006 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
11-09 09:56:21.349 22720 22720 I HotwordWorkerImpl: onReady
```

**Comment by poppahorse** [comment]
@andybbtt11 slight work around for now (which semi works, as sometimes the local build option disappears for no good reason), but if you install an older version, scan the QR, then it comes up in the menu and you can launch from there without the need for the camera

total PITA however if it drops from the menu, and you have to cycle installing the old then new version each time :(

**Comment by pre** [comment]
There's an experimental client version "Crosswalk 17 (16bit)" availalble in the Build Service. (Click "show older versions" and see the bottom).

Crosswalk 17 provides 64bit compatibitlity. The build is completely untested right now, so pay heed. A proper release will be available soon.

**Comment by poppahorse** [comment]
does it make a difference that i was using webview, not crosswalk?

but will give that build a try, thanks!

**Comment by pre** [comment]
The QR code scanner plugin also required 64bit libraries, those are included in the test version mentioned above. If you got `couldn't find "libiconv.so"`then that issue should no longer appear.

**Comment by sunny061** [comment]
I don't see the Crosswalk 17 (64bit) option in the build service. I also have one device where the custom scanner crashes after tapping the (+) button to scan.

**Comment by pre** [comment]
64 bit compatibility is now available in Android 4.2.0, which is now available from the Build Service. Scanner will shortly be available in Google Play.

In the build service, arm+x86 build target will include arm, arm64 and x86 native libraries. There will be an option soon which will allow you to include only arm64 libraries.

**Comment by andybbtt11** [comment]
I requested a scanner app of the 4.2.0 arm+86 build, same crash scenario. Now my actual app is crashing as well with a 4.2.0 google play build of arm only. Going to keep trying various builds and report back.

**Comment by pre** [comment]
Currently only the arm+x86 build contains the arm64 native libraries. "Arm" build will only contain arm32 compatibility. An option to build arm64 only will be available shortly.

Is the issue that you had an arm-only build?

**Comment by ezramorse** [comment]
Android version
Android 4.4
Device
ZenFone 4 (A400CG) (ASUS_T

```
junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
	at junit.framework.Assert.fail(Assert.java:50)
	at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:193)
	at org.xwalk.core.XWalkPreferences.reflectionInit(XWalkPreferences.java:207)
	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:97)
	at com.appgyver.webview.XWalkRuntimeConfig.<init>(XWalkRuntimeConfig.java:22)
	at com.appgyver.runtime.standalone.chromium.StandaloneChromiumApplication.onCreate(StandaloneChromiumApplication.java:12)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4580)
	at android.app.ActivityThread.access$1500(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5257)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by pre** [comment]
@ezramorse Are you sure this error happened using the 4.2.1 version of the Android client?

**Comment by ezramorse** [comment]
Im positive. It happened again today at 9:54 AM PST on our freshest 4.2.1 build from this morning.

Its doesn't happen often. The last two times were on 4.4 Zenfone 4

**Comment by ezramorse** [comment]
ZenFone 4 (A400CG) (ASUS_T00I) is (on of) the problem device here

**Comment by calvinlai** [comment]
I can confirm @ezramorse 's finding that it is happening on Version 4.2.1 on an Samsung Salaxy S6 (Android 5.1.1). I've just did a fresh build on AppGyver Cloud Services 15 mins ago to test this.

<img width="862" alt="appgyver cloud services build 4.2.1" src="https://cloud.githubusercontent.com/assets/965728/12251269/7df0e6e6-b932-11e5-85d0-50905c8ee9c5.png">

## App crashes on launch
App crashes on launch with "Please have your activity extend XWalkActivity for shared mode" exception.

<img width="300" alt="Crash on launch" src="https://cloud.githubusercontent.com/assets/965728/12251270/80ca082a-b932-11e5-8f59-3e121a792af4.png">

I'll give 4.2.0 a try.

**Comment by calvinlai** [comment]
## Select "ARM and x86" for 64 bit support
Just for everyones benefit, make sure to select "**ARM and x86**"  for 64bit CrossWalk support. This should get rid of the "Please have your activity extend XWalkActivity for shared mode" exception. It is not clear in AppGyver Cloud Service UI that that's necessary.

<img width="866" alt="appgyver_cloud_services" src="https://cloud.githubusercontent.com/assets/965728/12252189/e3f60136-b939-11e5-8a91-d98c2d87cf68.png">
