### ISSUE TITLE
Error at install steroids (Node 5 and NPM 3)

### ISSUE THREAD

**Issue by horochovec** [AppGyver/steroids#1078]
Environment 

horochovec: mediaglobe$ node --version
v5.0.0
horochovec: mediaglobe$ npm --version
3.3.6

npm WARN EPEERINVALID generator-steroids@1.0.20 requires a peer of yo@>=1.0.0 but none was installed.

**Comment by Leeds-eBooks** [comment]
npm 3 deprecates peer dependencies, could this be because of that?

**Comment by harsaharsa** [comment]
Yup, npm 3 doesn't work with Steroids CLI currently. Closing this as duplicate of https://github.com/AppGyver/steroids/issues/1055

**Comment by mansoor-spark** [comment]
Hi Harsa -
I downgraded my npm version 3 to npm version 2 but I still get the below error when installing Steroids:

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
/usr/local/bin/steroids -> /usr/local/lib/node_modules/steroids/bin/steroids
