### ISSUE TITLE
Navbar icons and text disappear - cannot build IOS apps higher than v4.0.6

### ISSUE THREAD

**Issue by thedeukalion** [AppGyver/steroids#1081]
Every app built with versions later than 4.0.6 has problems with icons in the navbar.

On Android I had to change path from "'/icons/navbar.svg'" to just "/icons/navbar.svg" than is without '.
Before that, icons were rendered with black rectangles.

Now, 99/100 times start up icons are distorted like 1px scaled to 48px or something. Changing views restores them to how they should look.

On IPhone, navigating to a second view, any view - with both <super-navbar> in the .html file or a coded navbar using "supersonic.ui.navigationBar.show()"-like code and then back removes the icons entirely and the Title making the entire navbar empty and just a background color. No update in code or anything is called when navigating back. Rotating the screen restores the icons and the title.

And, since this is kind of an important feature of the entire app. And since your newsletter of requirements of building with the new XCode version makes it kind of imporant to fix. Currently, to even be able to use our app I have to build with 4.0.6 and then risk the rejection of deploying the app to appstore, losing like 10 days of waiting on a rejection.

**Comment by rufiodev** [comment]
+1, we're having the same issue. The icons in the navbar get the wrong size until a user interaction on the header is done. This happens in dev builds (we're using crosswalk, arm, x86).

Possibly related: The scanner app in Android has the same issue; probably because it also has a higher default build base.

**Comment by thedeukalion** [comment]
2 months and no acknowledgement of it's existence. Great!

**Comment by harsaharsa** [comment]
Sorry for not picking up on this. So, there seems to be two issues:

1) **On Android, almost every time the nav bar icons are scaled wrongly when the app starts.** Changing a view restores them to how they should be. I assume this has been verified only in Crosswalk? *I could not reproduce this with the latest Scanner version using the code pasted below, so please post a repro app that shows this behavior.*

2) With iOS and Android, versions later than 4.0.6 exhibit a behaviour that when you do `layers.push` to a second view, any programmatic changes made with `supersonic.ui.navigationBar.update` get discarded and everything is reverted back to whatever was initialized with the `<super-navbar>` element.

However, if you set up your navigation bar without the `<super-navbar>` element (i.e. programmatically with `supersonic.ui.navigationBar.update` and `supersonic.ui.navigationBar.show`), everything works as expected

The code I tested with set up the native CSS like shown [in the guide](http://docs.appgyver.com/supersonic/guides/ui/styling-native-components/navigation-bar-styling-example/):

```
/* native-styles/ios.css */
#searchButton icon {
  background-image: url(icons/cog.svg)
}

/* native-styles/android.css */
#searchButton {
  background-image: url(icons/cog.svg);
}
```

and setting the navbar up with something like:
```
searchButton = new supersonic.ui.NavigationBarButton
  styleId: "searchButton"

supersonic.ui.navigationBar.update
  buttons:
    right: [searchButton]
```
