### ISSUE TITLE
Error at install steroids (Node 5 and NPM 2)

### ISSUE THREAD

**Issue by mansoor-spark** [AppGyver/steroids#1083]
I am unable to install steroids with Node 5 and NPM 2. Could you please help?

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
/usr/local/bin/steroids -> /usr/local/lib/node_modules/steroids/bin/steroids

**Comment by harsaharsa** [comment]
Even though the error message is given by Yeoman, Steroids should still work fine. If you run the `steroids` command, what happens?

**Comment by mansoor-spark** [comment]
Hi Hari -

Thanks for your response. I fixed the error.

Cheers,

Ali
