### ISSUE TITLE
Filesize getting bigger on Android

### ISSUE THREAD

**Issue by rufiodev** [AppGyver/steroids#1087]
We've got an Android app in distribution and it's file size keeps increasing every use of the application.

We tested with build mode on 4.0.6 and 4.2.1. At the moment Crosswalk, ARM and x86 is used. If the base of the app is 70 MB it can increase to over 160 MB. Has anybody else encountered anything similar?

Thanks in advance for any advice we can get.

**Comment by pre** [comment]
Android client version 4.2.1 includes arm32, arm64 and x86 native libraries. Each takes ~23 MB in the APK filesize.
