### ISSUE TITLE
If the Karma npm module is included, the Steroids CLI server crashes after modifying any file within the project folder

### ISSUE THREAD

**Issue by FearDread** [AppGyver/steroids#1088]
This issue only recently started occurring when upgrading steroids cli to version 4.1.+ and is affecting my entire development team.  I start the steroids server locally with normal `steroids connect` command and everything updates and launches correctly, even opening QR code in browser.  However when I attempt to modify any file within the project directory (save, open, close, change branches) the server immediately fails throwing:

``` bash
Detected change, running make ...

[TypeError: undefined is not a function]
```

... at which point I have to then restart the steroids server.  I have tried running with --live-reload option and it will still crash no matter what.

My team members are getting exact same behavior with a different error being thrown:

``` bash
Detected change, running make ...

[TypeError: Object [object Promise] has no method 'finally']
```

Again this started when we all upgraded to latest steroids cli version via `npm install -g steroids`.

We are all running Mac OSX computers with either "El Capitan" or "Yosemite" and have latest X-code installed.
Node Version: v0.12.7
NPM Version: 3.3.4
Steroids Version: v4.1.22
Bower Version: 1.6.8

Please let me know if any other software information may be needed to help discover what may be causing this issue for us, it is very intrusive in the development process as anytime we make a change to any file we have to restart the steroids server in order to test the changes.

**Comment by Ezku** [comment]
Hi, thanks for bringing this to our attention. Does this happen if you run `steroids connect` with the `--no-watch` flag and refresh manually? If you run `steroids make`, does that fail too? Have you tried updating your project's npm dependencies by deleting `node_modules` and running `steroids update`? Does this happen only on your existing project, or can you reproduce this by creating a new project with `steroids create`? Thanks for any further information.

**Comment by FearDread** [comment]
I will try creating a new project and see if the same issue happens, I have tried deleting `node_modules` and running `steroids update` and get the same results.  Running `steroids make` works the first time and loads correctly but crashes as soon as any change is made to any project file.  That is the strange part is that it always starts the first time correctly with out error, then as soon as something changes it fails.  

I will get back with the results of creating blank project and will also try the `--no-watch` option and see what happens.

Thank you for quick response on this matter.

**Comment by FearDread** [comment]
Running `steroids connect` with the `--no-watch` option and then manually refreshing still causes error and steroids server crash.  Will update with results of creating new project, we also may have found another reason for the failure which may have something to do with our `package.json` devDependencies.  

Also we are looking into a possible cause being via `ng-cordova` libraries.

Will update with latest soon.

**Comment by FearDread** [comment]
Creating a new project from scratch with `steroids create` works as expected and does not have this issue, so by that guess it means the problem lies within our projects code base somewhere and its causing the steroids grunt task that re-builds the project to fail.  

We found that removing some of the npm modules from our `package.json` file actually solved one of the issues where it was saying 
```bash
[TypeError: Object [object Promise] has no method 'finally']
```
... but did not solve the other issue of `undefined is not a function`, and the modules that we removed are actually needed to run our tests both locally and via travis CI, ( using jasmine, karma, grunt build to run tests ).

Are there any known issues with the npm modules needed to run karma or jasmine via grunt and the steroids cli?

I will continue to debug and attempt to find the culprit of this issue and update this accordingly.  Please let me know of any know issues with npm modules and the steroids cli grunt tasks.

**Comment by FearDread** [comment]
So the root of the issue appears to be with the `Karma` npm module, as soon as I remove that module from project `node_modules`, the steroids cli has no issue restarting / rebuilding when modification made.  

***

Not sure if this should stay as an issue for steroids or if it should be brought up on the karma npm module repo.  We definitely need the karma npm modules for our unit tests, which uses karma, jasmine and grunt.

**Comment by harsaharsa** [comment]
Thanks for the in-depth research on this. Since Karma is not an officially supported way of doing unit tests at the moment, this goes more into the "Karma should fix this" bucket, but if you find a way to fix CLI, we'd be happy to get a PR together. Sorry for the harsh prioritization/scoping! I updated the issue title to match your findings.
