### ISSUE TITLE
Android ~4.4 Webplatform Data Subscribe/Publish not working

### ISSUE THREAD

**Issue by andybbtt11** [AppGyver/steroids#1089]
Any type of subscribe/publish in android 4.4 webplatform (specifically appgyver build 4.0.6) does not work for me. 

I am unable to run crosswalk due to crashes/slowness on 4.4 (5+ it's fine). 

Anything about 4.0.6 does not allow inAppBrowser windows to open without crashing. Crosswalk and Web Platform. 

Not sure where to go from here.

**Comment by harsaharsa** [comment]
The InAppBrowser crash is something that's being worked on right now.

Is the subscribe/publish working on earlier build versions?
