### ISSUE TITLE
Steroids doesn’t work with Node 5.2 and npm 3.5.2 

### ISSUE THREAD

**Issue by mischah** [AppGyver/steroids#1090]
Hej there,

I just wanted to quickly checkout the AppGyver eco system according to the [Supersonic tutorial](http://docs.appgyver.com/supersonic/tutorial/first-mile/#overview):

> In this tutorial, we will be going through the few simple steps needed to get an app running on your device. This section will take 5-10 minutes to complete […]

But man, that was a hell of a ride and took more than one hour to simply run the demo app in the emulator :dizzy_face:

Here are my pain points:
- https://github.com/AppGyver/grunt-steroids/issues/15#issuecomment-164954948
- https://github.com/AppGyver/grunt-steroids/pull/32
- https://github.com/AppGyver/generator-steroids/pull/19
- https://github.com/AppGyver/generator-steroids/pull/20

**Comment by harsaharsa** [comment]
Thanks for these – we'll review the PRs. It's a known issue that Steroids CLI has issues with npm 3 – we've had to prioritize other things ahead of npm 3 compatiblity, since npm 2 works great.

Just so we know what we're testing – with these PRs, everything works great with npm 3?

**Comment by mischah** [comment]
> Just so we know what we're testing – with these PRs, everything works great with npm 3?

Yes. It works after these changes.

Beside of deploying the app to an android emulator. But I guess that’s a whole different story :grin:

**Comment by harsaharsa** [comment]
Just to give an update – this is still coming up on the backlog, just swamped with other things currently!

**Comment by harsaharsa** [comment]
Did some work on this, but there's a lot of moving parts, especially if we don't want to break everyone's setups on Node.js 0.12.x. We'll see how we proceed with this, but for now, the recommendation is just to use Node.js 0.12.x (with Node Version Manager, if possible) and everything will work fine.

**Comment by Luttik** [comment]
This problem is solved quite easily. Steroids creates a package.json with if I recall correctly only `"grunt-steroids:"1.*"` as devDependency. If you replace this with 
```
"devDependencies": {
  	"grunt-contrib-clean": "1.0.0",
  	"grunt-contrib-coffee":"1.0.0",
  	"grunt-contrib-concat": "1.0.1",
  	"grunt-contrib-copy":"1.0.0",
  	"grunt-contrib-sass":"1.0.0",
  	"grunt-extend-config":"0.9.5",
	"grunt":"1.0.1",
        "grunt-steroids": "*"
  }
```
and then run npm update it does work. The steroids crew could simply prevent this problem for new users by delivering the package.json with the peer dependencies explicitly noted in the package.json.
