### ISSUE TITLE
Phone not compatible with new scanner version?

### ISSUE THREAD

**Issue by FearDread** [AppGyver/steroids#1092]
WTF happened here, I have never had incompatible issue and now I cant install scanner application via Android play store due to it saying "my device is not compatible with this version".  Never has it said this for my phone. 

Android version is 5.1.1
Phone Model is LGMS345 ( LG Leon LTE ).

I have been using the scanner app for a long time now and had to uninstall due to it not working correctly (seems to happen alot).  But when I go to re-install now its incompatible?  Give me a break.

Please let me know which repo this issue should go under if it is not supposed to go here ..

Thanks...

**Comment by harsaharsa** [comment]
Sorry for not picking up on this, just gearing back up after the holidays. Do you have access to the Android LogCat logs to show what the exact error is? Or does it not let you even start to download it? Are you installing the vanilla Scanner or the Enterprise scanner?
