### ISSUE TITLE
Performing layer.push() on a layer with 2 different animations will fail.

### ISSUE THREAD

**Issue by ghost** [AppGyver/steroids#1096]
Currently, I am trying to push() a layer into the view using the code: 

`supersonic.ui.layers.push("modal", {animation: supersonic.ui.animate('slideFromTop', {duration: 0.3})});`

After the `push()` above, I `pop()` it and tried to `push()` the layer into view again, but using `'slideFromRight'` instead of `'slideFromTop'` in the animation. By doing this, the layer is pushed in and displayed blank, dark-blue-ish screen instead.

It seems that you can not push a layer into view with multiple animations, is there a way to work around it?

**Comment by harsaharsa** [comment]
Sounds like a weird bug. Is this on iOS? What if you initiate a new View object that's targeting the same WebView?

**Comment by blanedaze** [comment]
Erm, sorry for being this late...

No, I didn't tested it on iOS.
I don't understand the second question, are you saying to create 2 View object pointing to a single WebView that use different animations?
