### ISSUE TITLE
Android Back Button Handler not triggered in initial tab view

### ISSUE THREAD

**Issue by stephan-klein** [AppGyver/steroids#1097]
Hi,

on the initial view of a tabbed layout the Android Back Button Event Handler is not triggered. Instead the app is closed when back button is pressed.

i tried:

```
supersonic.device.buttons.back.whenPressed(function () {
  console.log("Device back button was pressed.");
});
```

and also:

```
document.addEventListener("backbutton", function () {
  console.log("Device back button was pressed.");
}, false);
```

I tried to wrap it inside device ready event handler. But this also doesn't help.

It works on another tab (non initial) in the same app. It also works on the initial tab when going to another tab then going back to the initial tab then pressing back. It also works on a non tabbed (rootView) layout. But never on the initial tab origininally displayed after the app has loaded.

I tested this on Android 6. Not sure about older Android versions.

A simple example app reproducing the issue can be found at https://github.com/stephan-klein/appgyver-backbutton-issue.

**Comment by kaiserlos** [comment]
I don't work with tabs and without the navigation bar and my android back button also always closes the app, even if it just should pop the layer...

In my case the event handler is triggered but without a chance to stop the app from closing.

**Comment by stephan-klein** [comment]
I found a workaround for this.

In the controller of the first tab simply execute `supersonic.ui.tabs.select(0);` This does not make any sense but it prevents the issue and back button event handler is triggered.

@kaiserlos: On which android and supersonic native runtime version are you ? There were already some fixes for backbutton related issues in the past.
