### ISSUE TITLE
Supersonic.media.camera.takePicture crash after taking the picture (Android)

### ISSUE THREAD

**Issue by AndreaDrago** [AppGyver/steroids#1098]
Hi everyone,
I tried taking a picture using

```
supersonic.media.camera.takePicture(options).then (result) =>
  ...
```

(in coffeescript)
The camera opens up, it let me take the photo, but even before accepting or discarding the photo, the scanner app already crashed.

These are the option i'm giving to the function:

```
options = {
  quality: 50
  allowEdit: false
  destinationType: "dataURL"
  targetWidth: 100
  targetHeight: 100
  encodingType: "png"
  saveToPhotoAlbum: false
}
```

Of course these targetWidth and targetHeight are just for testing. I tried even without them, but it's still crashing. I don't know why, but after some changes in the code (not related to this section), sometimes it works, even for just one or two times.
The code for taking the picture:

```
supersonic.media.camera.takePicture(options).then (result) =>
  challange_service.postAnswer(@challange._id, result)
    .success (data) =>
      user_service.getMyUser()
        .success (data) =>
          challange_service.getChallangeById(@challange._id)
```

The camera callback is not even firing before crashing.
I've tried changing the options, but without any result.

Tested on Samsung Galaxy Trend Plus, Android 4.2.2, Appgyver Scanner v. 4.2.1

**Comment by harsaharsa** [comment]
Thanks for the report! Is it possible for you to get a Logcat output of the crash from the Android Developer Tools? Camera is working fine on our test devices, so it's hard to figure out what's wrong without the error message.

**Comment by AndreaDrago** [comment]
Hi, thanks for the answer,
Now i'm testing on a different device and it seems to work flawlessly. I can't test it on the other device anymore, because i tried re-installing the scanner application, but it says that my android version is not supported (even if it was working just until now...). If i'll be able to install the scanner again, i'll post the logcat about the error. Do you know how to filter this logcat, however? Because i saw that there were many many (useless) logs in the output...

**Comment by kaiserlos** [comment]
Having the same, it crashes in 70% of my tries ... only on android.

**Comment by kaiserlos** [comment]
Here we have some Logs, as I said it's really randomly and already testet on different devices. 

My test and log device: Android 4.4 // Motorola Moto G 
Build: Crosswalk, 4.2.2e (also happens on a 4.0.6 build)

Tried with fileURI and dataURL as destinationType.

[log2.txt](https://github.com/AppGyver/steroids/files/187525/log2.txt)
[log3.txt](https://github.com/AppGyver/steroids/files/187523/log3.txt)
[log.txt](https://github.com/AppGyver/steroids/files/187524/log.txt)
