### ISSUE TITLE
$http requests not working with mobile data but only under WIFI

### ISSUE THREAD

**Issue by arcaste** [AppGyver/steroids#1102]
Hello there, I have a strange problem using the AngularJS `$http` service.
Using an _HTC one mini 2, android 4.4.2,_ I'm not able to send requests using the mobile data. Under WIFI everything works fine but as soon as I switch to the 4G I get the following error message:
`XMLHttpRequest cannot load "<server address>". No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 411.`
- Those are the headers from the WIFI connectivity

![screenshot from 2016-02-01 12 07 43](https://cloud.githubusercontent.com/assets/14996806/12717513/a7d4b80a-c8e8-11e5-8275-8981f2404567.png)
- Those are the headers while under 4G

![screenshot from 2016-02-01 12 01 02](https://cloud.githubusercontent.com/assets/14996806/12717777/7655bbb0-c8ea-11e5-816b-45ca6b813a25.png)

I tried using another android device, 5.0.1, and it works. Also on the server side CORS is already configured. I really can't figure out what the problem could be.

**Comment by rpatil** [comment]
Faced the same Issue. But the problem with my code is private IP. I am using private IP for API request. As I replace with public IP, system is working fine.
Please try this and let us know if you got success.
