### ISSUE TITLE
Outdated default plugins (Android)

### ISSUE THREAD

**Issue by bilalsoomro** [AppGyver/steroids#1104]
I see they are all pretty much outdated according to the link below. Is there a reason why they haven't been updated? It would be great if they can be updated to the latest compatible versions. One issue I am facing is that the defualt cordova dialogs looks very weird on my lollipop android device. Is anyone also facing this issue?

http://docs.appgyver.com/tooling/build-service/plugins/default-plugins/

Thanks

**Comment by joedaniels29** [comment]
Yeah, the whole thing is out of date. The version of the media plugin is so out of date that it just doesn't work. I had to create my own microphone plugin in objc and wrap in js to make it work.  
Lol you should star it 😄 https://github.com/joedaniels29/cordova-plugin-mediocre-media
