### ISSUE TITLE
Android Google Play (CrossWalk, x86 only) build issue

### ISSUE THREAD

**Issue by bilalsoomro** [AppGyver/steroids#1108]
Hi, 

I build an Android Google Play (CrossWalk, x86 only) build using the build service and published it to the playstore. However, devices with ARM processors are able to search and install this build even though it's not meant for their device. After launching on the app after download, it instantly crashes.

I manually installed and tested the Android Google Play (CrossWalk, ARM only) build and it is working without any issues. But the device finds the x86 version on Google Play instead. How can I fix this?

Thanks

**Comment by aminecmi** [comment]
@sunny061 in the play store, you can specify wich devices can use your APK, and then these devices won't be able to download your app.
