### ISSUE TITLE
Allow custom Simulator builds

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#112]
Allow custom Simulator binaries to be built, so that the iOS Simulator can be used with e.g. custom plugins.

**Comment by mtomic** [comment]
It might be a good time to revisit this team :-) :+1:

**Comment by harsaharsa** [comment]
@mtomic custom Simulator builds are now available in the Build Service! They use Debug Scanner provisioning profile.

Will be keeping this issue open until we have an accompanying guide out.

**Comment by mtomic** [comment]
@harsaharsa awesome :+1: Keen to see the guide on how to use it!

**Comment by pre** [comment]
The Build Service support is now implemented. I'll close this issue.

The missing part is Steroids CLI support, there's a ticket for that in https://github.com/AppGyver/steroids/issues/848 -- there are also instructions how to manually use your custom simulator in Steroids CLI before the official support is released.
