### ISSUE TITLE
iOS debug builds not working

### ISSUE THREAD

**Issue by andybbtt11** [AppGyver/steroids#1121]
All of my iOS apps are not building. I get a message saying it failed with no reason as to why.  I have reuploaded all of my certs/provisions but still get the same errors.  I have tried 5.0.1-rc1 as well as 4.0.10.

Anyone noticing this or is it just me?

Thanks

**Comment by rafaeluzzi** [comment]
@andybbtt11 if you are using any github plugins check if there is one updated recently.

**Comment by andybbtt11** [comment]
good idea @rafaeluzzi. I tried removing all plugins, i completely created new dev certs and profiles, changed version number, reuploaded, etc.  Still I get the vague failed error.  I also tried removing both of my github plugins from my build settings still nothing.

**Comment by racingsolution** [comment]
I was able to build my IOS app with 5.0.1-rc1 .. only have 1 plugin.. didn't change anything in my settings.  No errors.

**Comment by christofferh** [comment]
We had an issue with build assets which has been resolved. 

@andybbtt11 let us know if you're still getting errors with new builds.

**Comment by andybbtt11** [comment]
@christofferh working now. Thank you.
