### ISSUE TITLE
steroids-cli can neither list nor launch iOS simulators after XCode 8 update

### ISSUE THREAD

**Issue by erkmene** [AppGyver/steroids#1122]
Using `AppGyver Steroids² 4.1.26`, in connect page the list looks like this:

![image](https://cloud.githubusercontent.com/assets/1096880/18564673/453f3b60-7b95-11e6-9bb3-d3c366f4ff3d.png)

And when clicked, this button results in:

![image](https://cloud.githubusercontent.com/assets/1096880/18564702/64bcc55c-7b95-11e6-8e13-a1615bd23b97.png)

This is also the case in cli

![image](https://cloud.githubusercontent.com/assets/1096880/18564708/706e2bf2-7b95-11e6-864f-2776a229b391.png)

**Comment by erkmene** [comment]
The problem with listing seems to be caused by rejecting XCode versions other than 6 and 7.

https://github.com/AppGyver/steroids/blob/master/src/steroids/Simulator.coffee#L32-L45

A possible fix would be changing this with a minimum version check (rather than explicity checking the version numbers.) Something like below would fix it:

```coffeescript
  validXCodeVersion: ->
    new Promise (resolve, reject) ->
      versionRegex = /Xcode (.*)/
      minimumXcodeVersion = 6

      xcodeVersionSession = sbawn
        cmd: "xcodebuild"
        args: ["-version"]

      xcodeVersionSession.on "exit", ->
        installedVersion = xcodeVersionSession.stdout.match(versionRegex)
        valid = installedVersion && parseFloat(installedVersion[1]) > minimumXcodeVersion
        if valid
          resolve()
        else
          reject new UnsupportedVersion "XCode needs to be at least version 6 to run the simulator."
```

Unfortunately, the problem with *launching* the simulator can not be solved by this. The ios-sim package exits with the following error when a launch is attempted:

```
Failed to find class DTiPhoneSimulatorSystemRoot at runtime.
```

**Comment by harsaharsa** [comment]
This is in the works, I'll update you when we know more!

**Comment by wiwat-tharateeraparb** [comment]
+1

Any fixes?

**Comment by cwilkenloh** [comment]
+1

Same problem here...

**Comment by erkmene** [comment]
IMO it'd be better if the issue remained open until a fix was in place. This would prevent it from being perceived as resolved and also discourage duplicates.

**Comment by harsaharsa** [comment]
Whoops, the close was accidental. Sorry for that. Discouraging duplicates definitely – I couldn't find this one so I created a new one already.

We're at a point in our research that updating the `ios-sim` dependency to its latest version (external command-line tool by PhoneGap to launch the iOS Simulator) helps launch the Simulator, but the Scanner app still crashes. Investigation continues.

**Comment by hoorayinteractive** [comment]
+1

**Comment by harsaharsa** [comment]
Fixed now in v4.1.2.7 – didn't set the update notice for Steroids CLI yet, but you can update with e.g. `npm update steroids -g`.

There's a known issue that the iOS Simulator device dropdown in Connect Screen shows multiple redundant/unsupported device types, including watchOS and tvOS.

Report any further issues here!

**Comment by wiwat-tharateeraparb** [comment]
With 4.1.2.7, I got this error `"TypeError: Right hand side of instanceof is not an object - undefined:undefined"` when launching iOS 10 simulator and it hung at scanner screen.

**Comment by wiwat-tharateeraparb** [comment]
Changed to use `webcomponents-lite.js` seems to help. Testing continues.

**Comment by wiwat-tharateeraparb** [comment]
Found out that this old bug which was resolved by the workaround (https://github.com/AppGyver/steroids/issues/1042) has come back.

**Comment by mgeschiere** [comment]
+1

**Comment by markterrill** [comment]
Doesn't work at all. I changed the Simulator.coffee to accept (6|7|8) but still no joy
