### ISSUE TITLE
iOS Store Submission Missing Assets

### ISSUE THREAD

**Issue by justincolangelo** [AppGyver/steroids#1123]
Using Sierra and Application Loader (beta and not), I am unable to submit my application. 

[Image 1](https://postimg.org/image/dnlhr9bw3/)

[Image 2](https://postimg.org/image/g3nb53tyr/)

Showing the package contents of the appstore build (5.0.1) reveals the images are actually there, and the info.plist references them. 

Using the non-beta version of Application Loader, the system reports that there is no app bundle in the package.

**Comment by harsaharsa** [comment]
What's the app ID/build ID in question? We were able to submit app store packages just last week, so let's get to the bottom of this.

**Comment by justincolangelo** [comment]
AppGyver App ID: 112914 Build 5.0.1
