### ISSUE TITLE
Custom Simulator Scanner not starting on macOS Sierra & Xcode 8

### ISSUE THREAD

**Issue by mgeschiere** [AppGyver/steroids#1128]
Hey,

I have updated my mac to macOS Sierra and Xcode 8.
Now the custom simulator scanner stoped working. The app wil start up, but terminate imidiatly.
I have updated devroids and build a new simulator scanner in the cloud. But still isn't working.

Any ideas?
Thanks!

**Comment by EdwinRikkers** [comment]
+1

**Comment by kennethjohnbalgos** [comment]
Try including `webcomponents-lite.js` instead of `webcomponents.js` from your `layout.html` file.

**Comment by harsaharsa** [comment]
Yes, the app crashing issue should be fixed with `webcomponents-lite.js`. Closing until further repro.
