### ISSUE TITLE
Tab bar replace, Icons missing, iOS 10

### ISSUE THREAD

**Issue by Schurke** [AppGyver/steroids#1130]
Found an issue and a workaround.

Issue: After a tab bar replace, you'll have no tab bar icons. This likely has to do with Pixate not having been updated.

Use Case: 
Define a tab bar in structure, set up your icons through native css

Run the replace command at runtime to change out your tabs (maybe your user logged in and was expecting new options to show up).

The new tabs will not pick up the icons from the native css (the tabs will have text labels and function normally but will have blank spaces where icons should be).

Workaround: 
Note that this doesn't work using svgs, instead use pngs with @2x as part of the filename so that pixate knows to half the size on them (filename@2x.png). In my case, I was using 60x60 images.

Define the icon in the tab objects in both structure and in the replace function as a param (legacy steroids style):
title: "whatever"
location:"whatever"
icon:"icons/filename.png"

The icons should show up normally now... at the cost of dropping your svg icons...

Also note that this doesn't address any of the tab bar colour styling issues introduced with iOS 10.

**Comment by nem-c** [comment]
@Schurke Way to GO! Thank you
