### ISSUE TITLE
XCode Version and iOS simulator

### ISSUE THREAD

**Issue by gmaurano** [AppGyver/steroids#1136]
I already noticed this issue last year, after updating my XCode version to 8.0.
If you take a look at row 34 of this file:
https://github.com/AppGyver/steroids/blob/master/src/steroids/Simulator.coffee

you can catch the issue:

minimumXcodeVersion = /Xcode (6|7|8)./

If my xcode version doesn't match with minimumXcodeVersion (as it happen for 9.0 version), I get the following error message: "Please update to XCode 6 to run the simulator."

**Comment by bonoweb** [comment]
+1
I tried to change it to (6|7|8|9) but i can't start the simulator...

**Comment by hoorayinteractive** [comment]
+1

**Comment by nur-85** [comment]
How to run iOS simulator, if i have XCode 9?
I take error:
AppGyver Steroids command  
Please update to XCode 6 to run the simulator.

**Comment by gmaurano** [comment]
Below their answer through the AppGyver Cloud web panel:

> Hey,
> it looks like there's quite a few changes that have come with the new Xcode version to the underlying ios-sim project we use. https://github.com/AppGyver/steroids/blob/master/src/steroids/Simulator.coffee#L34 is the line with the version check, but https://github.com/appgyver/ios-sim would require updating also – it's 112 commits behind phonegap's master version.
> 
> We are phasing out the Steroids CLI in favor of Composer (and the whole of Steroids/Supersonic apart from Composer-dependent features is on a sunset path), so we likely won't be able to devote resources to fixing this. If you make a pull request to Steroids CLI with an updated ios-sim version that works, I'd be happy to review and merge it though.

**Comment by TomTom101** [comment]
+1
