### ISSUE TITLE
Cannot use cloud build service.  steroids deploy 

### ISSUE THREAD

**Issue by jptheripper** [AppGyver/steroids#1138]
Sun Mar 25 2018 15:43:48 GMT-0400 (Eastern Daylight Time) Zip created, timestamp: 1522007028644
Sun Mar 25 2018 15:43:48 GMT-0400 (Eastern Daylight Time) DEPLOY: Updating existing app with id 90457
Sun Mar 25 2018 15:43:49 GMT-0400 (Eastern Daylight Time) DEPLOY: Got cloud upload response

Error with: steroids deploy

TypeError: Second argument needs to be a buffer
  at Object.fs.read (fs.js:682:11)

**Comment by yangy46** [comment]
This is a problem with the reslter dependency using the obsolete fs.read function protocol. You can resolve this by updating restler with the pending PR.

https://github.com/danwrong/restler/pull/251

**Comment by rAthur** [comment]
I have the exact same issue and I don't understand how to solve it. 

@yangy46 I'm on Windows with Node 10.13.0 and NPM 6.4.1 how can I manage to make it work?

Thanks a lot!

**Comment by rAthur** [comment]
I eventually figured it out! 

I replaced the file `multipartform.js`, located in `C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\steroids\node_modules\restler\lib\multipartform.js` with [the one from the pending pull request from _restler_](https://raw.githubusercontent.com/danwrong/restler/63809c28cbcd0474e589ee5086f65bca68f7751e/lib/multipartform.js).

Then `steroids deploy` would trigger me a now error concerning the function `fs.close(fd);` inside it, so I went on line 133 of that file and simply commented that line. 

It's now working again! :)
