### ISSUE TITLE
Error with: steroids deploy

### ISSUE THREAD

**Issue by rAthusFr** [AppGyver/steroids#1144]
Hi! 

I reinstalled Appgyver Steroids because a customer needs a very urgent update, everything works until I'm trying to deploy, I'm getting this:

> Steroids Error
> Debug Log:
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) requiring C:\Users\rAthus\AppData\Roaming\npm\node_modules\steroids\package.json
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) package.json#version: 4.1.27
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) Updater: Looking for update: https://updates.appgyver.com/v1/steroids/latest.json?os=Windows_NT&version=4.1.27&from=deploy&user_id=20876&ionic=false&cordova=false
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) Starting push
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) Making with hooks.
> Wed Oct 31 2018 16:02:28 GMT+0100 (GMT+01:00) Running Grunt tasks...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Creating dist\__appgyver_settings.json ...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Creating dist\config.ios.xml ...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Creating dist\config.android.xml ...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Creating dist\config.json ...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Packaging project...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Removing existing zip...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Existing zip found and removed.
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Zipping with 7zip...
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Updater: updates.appgyver.com says that the latest version is 4.1.27
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) Zip created, timestamp: 1540998151975
> Wed Oct 31 2018 16:02:31 GMT+0100 (GMT+01:00) DEPLOY: Updating existing app with id 172404
> Wed Oct 31 2018 16:02:33 GMT+0100 (GMT+01:00) DEPLOY: Got cloud upload response
> 
> Error with: steroids deploy
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "buffer" argument must be one of type Buffer, TypedArray, or DataView. Received type number
>     at Object.read (fs.js:442:3)
>     at reader (C:\Users\rAthus\AppData\Roaming\npm\node_modules\steroids\node_modules\restler\lib\multipartform.js:118:13)
>     at C:\Users\rAthus\AppData\Roaming\npm\node_modules\steroids\node_modules\restler\lib\multipartform.js:129:10
>     at FSReqWrap.oncomplete (fs.js:141:20)
> 
> Runtime information:
> 
>         platform: win32 node path: C:\Program Files\nodejs\node.exe
>         arch: x64               node version: v10.13.0
> 
>         cwd: C:\Users\rAthus\Steroids\ispo-france-2017

Any idea on what to do? 

Thanks a lot!

**Comment by rAthur** [comment]
I eventually figured it out! 

I replaced the file `multipartform.js`, located in `C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\steroids\node_modules\restler\lib\multipartform.js` with [the one from the pending pull request from _restler_](https://raw.githubusercontent.com/danwrong/restler/63809c28cbcd0474e589ee5086f65bca68f7751e/lib/multipartform.js).

Then `steroids deploy` would trigger me a now error concerning the function `fs.close(fd);` inside it, so I went on line 133 of that file and simply commented that line. 

It's now working again! :)
