### ISSUE TITLE
ENV config

### ISSUE THREAD

**Issue by jakecraige** [AppGyver/steroids#58]
I would be awesome if there was some sort of environment config and you could set up on the steroids object. 

The scanner build would be in a `staging` environment, when you build for app store/play/ad hoc it would use the `production` settings, and when developing locally it would use the `development` environment

And of course you could manually set it during development to whichever you wanted. 

This is a very convenient feature that other frameworks provide and has many use cases. The main one for me is setting up where my API is. I've built an app before only to realize that I built it using my development url instead of my production one. 

Also, it really wouldn't be that hard to implement. I'd consider coding something up but I wouldn't be able to do anything with how the build service works so I'd be stuck after a certain point.

**Comment by benjamincharity** [comment]
15 months later... should I assume this is nowhere on the current roadmap? Even a DIY example or something would be awesome. This seems like something almost everyone would be running into. Do most people manually change keys and endpoints?

**Comment by harsaharsa** [comment]
Full-fledged Build Service API is something that's still upcoming, and env configs will be included there – there just hasn't been that great pull for this yet. People seem to be managing alright with manual changes/scripts to handle environments. (I do realize how suboptimal that is – we're doing our best to prioritize development on what has the biggest impact.)

**Comment by benjamincharity** [comment]
Thanks for the update @harsaharsa!

**Comment by bobstiles** [comment]
bump...

This is something that everyone must deal with. I would love if there was something in the build service API that allowed you pass in a couple of ENV vars at build time as well (to set the correct API endpoints)
