### ISSUE TITLE
ng-generator fails to install dependencies

### ISSUE THREAD

**Issue by Sampax** [AppGyver/steroids#589]
Running `steroids generate ng-resource` in a Steroids project tries to install some Angular dependencies, but fails because of a version conflict due to hardcoded dependencies in the generator code
![1__sampo_sampos-air-2____appgyver_support_repros_ngproject__zsh_](https://cloud.githubusercontent.com/assets/1540411/4842516/532cfeec-6026-11e4-9d8e-0d8573f6ed7c.png)

A quick fix is simple enough, the offending line being [here](https://github.com/AppGyver/generator-steroids/blob/master/generators/ng-resource/index.coffee#L26)

**Comment by harsaharsa** [comment]
`ng-resource` generator has been deprecated since Supersonic launch – closing this issue that had been left open accidentally!
