### ISSUE TITLE
backbutton event can only be fired at the root page (Crosswalk build)

### ISSUE THREAD

**Issue by bensonjs** [AppGyver/steroids#617]
At 4.0.0 Crosswalk build, the backbutton event is working fine when you first load the page. However, once you navigate to any other page or a tag within the same page, it stop working. Following is a sample that can demonstrate the issue. 

~~~
<!DOCTYPE html>
<html>
<head>
    <title>Back Button Example</title>

    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" charset="utf-8">

        // Wait for device API libraries to load
        //
        function onLoad() {
            document.addEventListener("deviceready", onDeviceReady, false);
        }

        // device APIs are available
        //
        function onDeviceReady() {
            // Register the event listener
            document.addEventListener("backbutton", onBackKeyDown, false);
        }

        // Handle the back button
        //
        function onBackKeyDown() {
            alert('are you sure?');
            document.write('<div>onBackKeyDown</div>');
        }

    </script>
</head>
<body onload="onLoad()">
<div>
    <a href="#Top">Top</a>
    &nbsp;|&nbsp;
    <a href="#Bot">Bottom</a>
</div>
</body>
</html>
~~~

**Comment by andre-luis** [comment]
I have a project created for Phonegap and I'm trying Steroids with it. The experience has been great so far, but one solution I gave that used the backbutton event is not working (apparently the only thing not working). The event listener is not being called (the breakpoint I put when debugging was not reached). It seems to be a problem related to this thread. Do you think I should open a new thread to discuss this, or should I give the details just here?

**Comment by andre-luis** [comment]
Just one more thing. It is not a legacy issue, I'm testing on an Android 4.4.2

**Comment by pre** [comment]
@andre-luis Please open a new issue with a code reproduction, we haven't heard any other reports that the back button wouldn't work atm.
