### ISSUE TITLE
Fix Push Plugin crash issues on Android

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#620]
* empty message causes a crash
* java.lang.RuntimeException: java.lang.Throwable: Warning: A WebView method was called on thread ‘IntentService[GCMIntentService-GCMIntentService-1]’. All WebView methods must be called on the UI thread. 
* occasional crashes when registering.

Refer to the community fork which is reported to work well: https://github.com/doomboy00/PushPlugin

**Comment by brahmikumar** [comment]
I am also having same problem, but push plugin working up to android 4.2.2 version,
for android 4.3.0 version and above, i'm getting this problem.

**Comment by pre** [comment]
There's the [new Push Notifications plugin](https://github.com/AppGyver/PushNotifications) available. 

I will close this issue because there problems were related to the old version of the Push Plugin. If you have new issues, [please report them here](https://github.com/AppGyver/PushNotifications/issues).
