### ISSUE TITLE
Loading screen not being displayed from Android drawer

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#637]
When calling the drawers.hide method to replace the center view from the drawer the loading screen is not being displayed as it happens with iOS.

**Comment by fidoboy** [comment]
Ok, now is not holidays. There is any hope? ETA? Please... :pray:

**Comment by adamgoose** [comment]
Referencing #830

**Comment by harsaharsa** [comment]
Closing this as duplicate of https://github.com/AppGyver/steroids/issues/644 (still no progress, sorry!)
