### ISSUE TITLE
SVG Icon Images in navigation bar title/buttons do not show up in Ad Hoc builds

### ISSUE THREAD

**Issue by mmelkko** [AppGyver/steroids#651]
Forum thread: https://forums.appgyver.com/#!/steroids-bugs:imagebutton-not-visible-in

**Comment by gchadid** [comment]
+1

**Comment by pre** [comment]
This is duplicate from https://github.com/AppGyver/steroids/issues/651

**Comment by fidoboy** [comment]
I'm sorry for reopening this closed thread, but I just want to notify all other participants on this thread. I've suggested this https://github.com/AppGyver/steroids/issues/632#issuecomment-78100318 that may be helps
