### ISSUE TITLE
Unload gives false success callback and does not unload view

### ISSUE THREAD

**Issue by mmelkko** [AppGyver/steroids#656]
Repro:
1. Preload a view
2. Unload the view
3. Try to preload the view again

Expected: View can be preloaded again
Actual result: View can't be preloaded because it has not been unloaded.

Works on iOS.

**Comment by fidoboy** [comment]
when this bug will be solved? there is no way to unload webViews on Android...

**Comment by fidoboy** [comment]
Not solved already with latest edge available today. Can't unload webViews on Android. This is going very very slow.... :(

**Comment by mmelkko** [comment]
Can you clarify @fidoboy ? I tested this with 4.0.4-edge6 with basic preload + unload + preload + unload + preload a few times and it worked fine.

**Comment by fidoboy** [comment]
well, my procedure is to call unload method from drawer, after the center view has been replaced; i use a timer to call the unload method. This is woking fine on iOS, but doesn't work on android; the webView is not being unloaded.

**Comment by pre** [comment]
Could you please post a code reproduction of the problem? We cannot reproduce your issue. :/

**Comment by pre** [comment]
There's another user who is reporting a problem with `unload` in combination with the drawer: https://forums.appgyver.com/#!/appgyver/steroids#crash-in-android-404-e-na::unread

I opened a new issue about that: #780

**Comment by fidoboy** [comment]
My procedure is to call the webView.unload() method from drawer. For example:

```
var webView = new steroids.views.WebView({
	'location': 'http://localhost/views/myview/myview.html',
	'id': 'http://localhost/views/myview/myview.html'
});
webView.unload();
webView = null;
```

this works fine on iOS, but it fails from Android.

**Comment by fidoboy** [comment]
Also, if you try to list currently loaded webViews from drawer it doesn't return the complete list.

**Comment by fidoboy** [comment]
This still fails with latest edge for Android. Returned error from the unload function is:

```A preloaded layer with identifier http://localhost/.....html could not be found```

**Comment by pentateu** [comment]
@fidoboy 
Your example is **not** valid:
```
var webView = new steroids.views.WebView({
    'location': 'http://localhost/views/myview/myview.html',
    'id': 'http://localhost/views/myview/myview.html'
});
webView.unload();
webView = null;
```
By doing: "webView = new steroids.views.WebView ..." you are creating just a javascript object with the web view parameters, but no physical web view is being created. You need to add the web view to the stack by:
 - pushing it to a layer; or
 - display as a modal; or
 - preload the web view ; or
 - display as drawer;
 - etc.

When you do "webView.unload();" right after creating the object and without adding it to the stack the expected result is to fail. iOS should also fail since there is no web view physically created with this id and url.

I'll fix the validation in iOS. 

I have added tests that prove that unloading a layer from a drawer works fine on Android as long as the web view exists and is not in use. Please see my comments on: https://github.com/AppGyver/steroids/issues/780

**Comment by fidoboy** [comment]
Yes, I know that the webView is not created. But it already it is. As I've already commented a few posts ago, the same code that I'm using is working fine on iOS. I'm creating a object referencing to the already created webView that it's loaded and I can see it. Then I call the replace method and when the webView is replaced I unload the old webView; and again, all of this is working perfectly fine on iOS as expected cause the webView exists

**Comment by fidoboy** [comment]
So, previous to my little example code here, the webView is being preloaded and displayed

**Comment by pentateu** [comment]
What is the error description in the failure callback ?

Can you share a repro project that shows this behaviour? 

I have just added new test cases to our testApp and it works as expected in Android.

There are only two validation in this API:
1. Checks if a preloaded web view exists with the ID provided -> Make sure the id is correct
2. Checks if the preloaded web view is not on longer in use -> Make sure the web view is no longer in use.

**Comment by harsaharsa** [comment]
I think @fidoboy's code should work – we'll go through it internally and get back to you!

**Comment by harsaharsa** [comment]
Let's keep the discussion in #780 so it's not split in two places! :)
