### ISSUE TITLE
inAppBrowser plugin problems with Crosswalk on Android when making POST or GET requests in background

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#657]
After some testing i've discovered that the inAppBrowser view closes itself if there is network activity on background when using it on Android. The plugin seems to work fine on iOS. To repro this, call a new inAppBrowser view and after this line, make a POST or GET to your server (for example), the browser view closes inmediately with no user interaction.

**Comment by pre** [comment]
InAppBrowser has now been updated in both Android and iOS clients. 

Please report here if it fixes this problem, thanks!

**Comment by fidoboy** [comment]
Cool! It could be really great to have it finally working on android. I'll create a new build right now and report back here my results :)

**Comment by fidoboy** [comment]
I've tested using 4.0.5-edge2 build. It doesn't work. It happens the same, the inAppBrowser opens and closes itself after 0.3 sec.

**Comment by fidoboy** [comment]
As i've mentioned in my first post, to repro this issue, call inAppBrowser plugin to display the view and then on next line, using angular, for example make a request to your restAPI or any other network activity... it makes inAppBrowser to disappear

**Comment by pre** [comment]
Could you open a ticket in the official InAppBrowser bug tracker? We can merge any changes coming from the upstream.

**Comment by fidoboy** [comment]
I have no account on that bug tracker. It doesn't seems to have issues management enabled on Github repo neither...

**Comment by fidoboy** [comment]
Ok, finally i've created a issue here: https://issues.apache.org/jira/browse/CB-8408 it could be useful if someone else could confirm the problem

**Comment by fidoboy** [comment]
Today i've discovered something weird related to this. Using platform web view it works fine; it's just when using Crosswalk build when this problem happens, so may be it's not related to the cordova plugin but to the browser engine or even steroids. Can you confirm the problem or share your experience?

**Comment by pre** [comment]
Are you using Cookies ? We had a similar issue with the FileTransfer plugin using a different cookie storage than which was actually used by the XWalkView.

**Comment by fidoboy** [comment]
No

**Comment by fidoboy** [comment]
I suppose that inAppBrowser may be uses cookies from websites I open using it. Not sure if this is what you ask. Anyway, problem is 100% related with Crosswalk, cause with platform webView it works fine. I've the feeling that it needs to be solved on Crosswalk and it's not caused by the plugin itself.

**Comment by fidoboy** [comment]
I've just created a new build using 4.0.5-edge7 and it seems that now it works fine and this problem is solved!! I'll need to do more in depth tests, but for the moment it looks fine for me

**Comment by harsaharsa** [comment]
Fixed for good in 4.0.5!
