### ISSUE TITLE
Second Mile tutorial: "Get position" button does not do anything

### ISSUE THREAD

**Issue by rph8** [AppGyver/steroids#674]
Hi *,

I am working through the Second Mile tutorial and something seems wrong:

In the sections "App logic in the controller" and "Access device hardware" the code seems not to work.

Specifically, both

angular  
.module('geolocation')  
.controller 'IndexController', ($scope, supersonic) ->    
# Controller functionality here    
$scope.getPosition = () ->
supersonic.ui.dialog.alert "Interstellar!"

as well as 

angular
 .module('geolocation')
 .controller 'IndexController', ($scope, supersonic) ->
		# Controller functionality here
		$scope.position = undefined

		$scope.getPosition = () ->
		  supersonic.device.geolocation.getPosition().then (position) ->
		    $scope.position = position

only lead to the error "ReferenceError: Can't find variable: $scope - undefined:undefined" (as in info) in the log in steroids connect.

Naturally, pushing the "Get position" button does not do anything at all.

What am I doing wrong?

Running steroids 4.0.2 on
OS X 10.9.5
latest scanner app (can't find version number)

Issue is the same on iOS and iOS Simulator running in OS X.

Raphael

**Comment by rph8** [comment]
Found the issue and am furious: The problem was that in the CoffeeScript controller files, Supersonic (or maybe CoffeeScript in general?) uses soft tabs instead of hard or SmartTabs. When I added the code however, I used smart/hard tabs i.e. actual tabs for indentation. Since that was inconsistent CoffeeScript seemed to default to soft tabs.
CoffeeScript does not seem to warn about this obvious mix up, which is why it took me a little while to figure it out myself.

I suggest that the example code be changed to SmartTabs, since this is the best compromise between soft/hard tabs.

**Comment by kkhire** [comment]
Hey rph8, i've never used coffeescript before. can you explain how I should change the example code so that it works? as I understand it, hard tabs are not to be used, so I spaced the lines out just as they looked with the tabs. It didn't make the prompt work on the app
