### ISSUE TITLE
Modals are not unloaded after modal.hide

### ISSUE THREAD

**Issue by mmelkko** [AppGyver/steroids#686]
Repro by watching from Chrome web inspector as follows:

1. Show non-preloaded modal (modal should appear in web inspector)
2. Hide modal (modal should not appear in web inspector anymore)

When modal is opened several times, each time an instance is left running.

**Comment by mmelkko** [comment]
Should be fixed in 4.0.4-edge3 and newer.

**Comment by fidoboy** [comment]
Ok, working now for modal views... but unload doesn't work for non modal webViews.
