### ISSUE TITLE
Android 5.0 blocks third party cookies, needs setAcceptThirdPartyCookies()

### ISSUE THREAD

**Issue by davesumter** [AppGyver/steroids#697]
Lollipop makes some [security changes to the default webview](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorWebView). One of these is blocking cross-domain cookies.

So if your app logs in from **localhost** to **example.com** and then uses a cookie to authenticate subsequent requests, the webview will no longer be able to use that cookie.

I've tested this and indeed cookies received from the server are no longer sent if being used for cross-domain requests (which is the only way hybrid apps can use them).

Would it be possible to give us a setting which allows us to enable third-party cookies? The runtime would need to then call setAcceptThirdPartyCookies() when creating the webview, as in [this example](http://tol8.blogspot.co.uk/)..

**Comment by pre** [comment]
API 21 is now included in the list of min sdk levels.

**Comment by davesumter** [comment]
great..!

**Comment by pre** [comment]
Delivered in Android 4.0.4-edge6
