### ISSUE TITLE
Crosswalk runtime crashes with an internal BrowserBlocking error

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#702]
This is a very common crash which occurrs at least on 

* Nexus 5 running Android 4.4
* Galaxy Tab 4 running Android 4.4

It's an internal Crosswalk issue.

Error message in logcat always contains "BrowserBlocking". This might have something to do with Crosswalk not releasing references to Android Assets, which causes an overflow when AppGyver Scanner project has been reloaded couple of times from Steroids CLI.

**Comment by pre** [comment]
This should be fixed by https://crosswalk-project.org/jira/browse/XWALK-3096 which we'll incorporate into the Android Scanner shortly.

**Comment by neophob** [comment]
any news about this issue?

**Comment by PeanutButterCo** [comment]
+1

**Comment by iDay** [comment]
+1

**Comment by pre** [comment]
This should now be fixed in Android 4.1.0 and newer.
