### ISSUE TITLE
Steroids never completes installation

### ISSUE THREAD

**Issue by AbdealiJK** [AppGyver/steroids#724]
Hi, I've been trying to install Steroids for the last 2 days ...

I am using Ubuntu 14.04

I first tried with the node/npm in apt-get and after sorting out permissions issues, I tried installing steroids. It got stuck in the point after "Dependencies and permissions look good! Starting Steroids installation ...". I left it on for about 8 hours and it kept showing the loading symbol ( that ascii character continuously changing : | / - \ | / ... )

Then I tried installing with nvm (after purging npm/node) written in the readme.md. I tried using `npm install steroids -g` ... without -g ... and also from the git repo using just `npm install`
This again gave me the same thing, it got stuck at the same point.

I have attached an image :
![image](https://cloud.githubusercontent.com/assets/2200743/5562915/20909fe6-8e6d-11e4-8507-7077c6994d13.png)

Any help appreciated

**Comment by pre** [comment]
Check that `which npm` will refer to the file in your nvm installation, eg `/Users/youraccount/.nvm/v0.10.25/bin/npm`

**Comment by Arkkimaagi** [comment]
Hi, I came here, because I encountered a similar problem.

I've been using Steroids for the past year and I have of course updated my install regulary.

Today when I tried to update steroids, it did not go trough with the install just like mentioned here.

```
$ npm update -g steroids
-
> steroids@4.0.8 preinstall /Users/arkkis/.nvm/v0.10.33/lib/node_modules/steroids
> node ./bin/preinstall




AppGyver Steroids² 4.0.8 installation

If you have any problems, please visit our forums at http://forums.appgyver.com
We are now trying to detect required dependencies and problems.
Some dependencies (like dtrace-provider) will print ugly warnings to the screen, but everything should be fine.
 
  - The AppGyver team (contact@appgyver.com)
 
 
Starting installation in ...
3
2
1
Lift-off!


Checking for compatibility with Node.js version v0.10.33 ... OK

Checking for required components ...

  Found git, good.

Dependencies ... OK

Checking $HOME/.npm ownership, making sure that 'arkkis' owns everything ... OK
Checking $HOME/.npm write acess, making sure that 'arkkis' has write access ... OK

Dependencies and permissions looks good! Starting Steroids installation...

```
After waiting for a good while, I ```ctrl+c``` escaped and tried to do a ```npm install -g steroids``` with similar results.

Here's my environment:
```
$ nvm --version; nvm alias; node -v; npm -v; which npm
0.17.3
default -> 0.10 (-> v0.10.33)
v0.10.33
2.1.5
/Users/arkkis/.nvm/v0.10.33/bin/npm
```

Please notice that I did not change anything on my system prior to doing the update. What would you recommend?

**Comment by Arkkimaagi** [comment]
Nevermind, after disabling little snitch (firewall), the install started rolling.

**Comment by luisreyes** [comment]
Ok for a while I had the same issue... after making sure I had NVM installed properly I ran the installation again. At first I thought it wasn't working until I looked at the .npm folder and noticed a lot of dependencies being installed. It took like 3-5 mins but it's all good now.

**Comment by pre** [comment]
Good to hear.
