### ISSUE TITLE
Store submissions rejected with iOS >=4.0.3-edge1 due to usage of a private API 

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#728]
![screenshot 2014-12-30 13 21 04](https://cloud.githubusercontent.com/assets/63895/5577171/bde17dcc-9013-11e4-8ddf-48145ceb3468.png)

**Comment by Mileto** [comment]
+1

**Comment by sledgecry** [comment]
+1

**Comment by pre** [comment]
Hi, could you try again with iOS 4.0.3-edge3 ? It should fix this issue.

**Comment by unknownexception** [comment]
@pre sorry for late answer, yes, the problem has gone, thank you!
