### ISSUE TITLE
Empty Navigation Bar is displayed when nav bar is not defined (Android 4.0.4-edge3)

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#729]
Repro:

* Create an example Steroids project which does not display a Navigation bar 
--> empty navigation bar is visible (expected: no nav bar)

Not affected: Scanner 4.0.3 (Google Play)
Affected: Scanner and Standalone 4.0.4-edge3

Workaround: 

Hide navigation bar manually with `supersonic.ui.navigationBar.hide()` or `steroids.view.navigationBar.hide()`

**Comment by pre** [comment]
Possibly related: https://forums.appgyver.com/#!/steroids-native-ui:hiding-navigation-bar-in-an

**Comment by julienroubieu** [comment]
+1. 
I have the same issue with a pure Cordova app (no steroids-js, no app.coffee) using only the build service.

**Comment by Codemax999** [comment]
I have the related issue where the gap is shown after preload replace of web view. Refreshing the page fixes the problem, but would like to not have to do that.

**Comment by sebmartel** [comment]
+1

**Comment by roberto-robles** [comment]
+1

**Comment by Codemax999** [comment]
Have any of the new edge builds corrected this?

**Comment by pentateu** [comment]
Will be fixed in the next edge. The pull request is done and will soon be tested and released.

**Comment by pre** [comment]
4.0.5-edge4 includes this fix.

**Comment by harsaharsa** [comment]
Fixed in 4.0.5!
