### ISSUE TITLE
Crash with EmptyStackException when exiting application with Back Button

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#731]
![appgyver x-2](https://cloud.githubusercontent.com/assets/63895/5577875/4bef3cf8-9023-11e4-93ad-9af9dc231606.jpg)

https://forums.appgyver.com/#!/steroids:android-steroids-exception

**Comment by sebmartel** [comment]
+1

**Comment by pre** [comment]
This is now fixed in 4.0.4-edge4. 

However, I wasn't able to reproduce the crash on Android 4.3, 4.4 or 5.0 using platform webview or Crosswalk (both Scanner and Standalone). Could you please check if this fixes the issue for you? I made a check for the empty stack condition, so this exact crash will not happen. So let me know if you find that there are side-effects.

**Comment by pre** [comment]
Finally got reproduction: back button must be clicked during app start while splash screen is visible.

After the fix in 4.0.4-edge4, there's now a different issue
~~~
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.app.Activity.getIntent()' on a null object reference
            at com.appgyver.ui.ViewStack.shouldHideSplashScreen(ViewStack.java:198)
~~~

**Comment by pre** [comment]
Fixed in 4.0.4-edge5

**Comment by roberto-robles** [comment]
Still randomly happening to me, here is how I trigger it: 

User opens the app, then switch to a email client or browser and click on a custom-url for opening the app again, the app goes to the front gain but the splashscreen never goes away. If I tap on the back button it goes to a black screen.

It works fine if I click on the custom-url and the app is not running. (it opens the app, and after a few seconds the splashscreen goes away and shows my main view)

**Comment by roberto-robles** [comment]
I tried to log for some errors using LogCat or Chrome inspector and nothing seems to be triggering an exception.

**Comment by pre** [comment]
@roberto-robles Has this happened for you prior to 4.0.4-edge4 or did this start happening after 4.0.4-edge4 ?

**Comment by roberto-robles** [comment]
@pre This happened after 4.0.4-edge4. I can provide to you my build Id so you can verify my Use case.
