### ISSUE TITLE
Application crashes in Samsung Galaxy Note 3

### ISSUE THREAD

**Issue by mikkol26** [AppGyver/steroids#734]
My steroids application crashes all the time in Samsung Galaxy Note 3. The same application is stable in every other device I have tested with including: Moto G, Sony android devices, Nexus 5, Galaxy S5 mini, Galaxy S tabs, different iPhone versions. The crash happens 100% of time and always during the few seconds after opening the app and going to a specific view.

This issue has been valid with all the steroids versions I've tested with the latest being
Steroids 3.5.9
4.0.4-edge3

According to trace, the reason always is as follows

12-30 10:14:48.958  16792-16792/com.myapp.business.scanner D/dalvikvm﹕ GC_EXPLICIT freed 4085K, 16% free 39410K/46812K, paused 3ms+4ms, total 30ms
12-30 10:14:48.958  16792-16792/com.myapp.business.scanner D/com.appgyver.ui.TitleBarContainerView﹕ presenting webview: AGWebView -> URL: http://localhost//views/flyer/list.html uuid: c896b059-b14f-434d-96e5-5fd42cfacf3d
12-30 10:14:49.008  16792-16792/com.myapp.business.scanner D/dalvikvm﹕ GC_EXPLICIT freed 159K, 16% free 39391K/46812K, paused 3ms+5ms, total 31ms
12-30 10:14:50.258  16792-17154/com.myapp.business.scanner W/Adreno-GSL﹕ <sharedmem_gpumem_alloc_id:1489>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
12-30 10:14:50.258  16792-17154/com.myapp.business.scanner E/Adreno-GSL﹕ <ioctl_kgsl_sharedmem_alloc:1590>: ioctl_kgsl_sharedmem_alloc: FATAL ERROR : (null)
12-30 10:14:50.608     839-1310/? I/ActivityManager﹕ Process com.myapp.business.scanner (pid 16792) (adj 0) has died.

the longer version of the log can be downloaded here: https://www.dropbox.com/s/5dgj9t535elkp6n/log1%20%281%29?dl=0

**Comment by pre** [comment]
The crash log is filtered to show only the com.myapp.business.scanner so the actual crash message is not visible (it's a Crosswalk crash). Even without the stack trace I believe this is the same issue: https://github.com/AppGyver/steroids/issues/698

Currently Crosswalk seems to have a memory issue in Android 4.4. Please check #698 for further details.

**Comment by mikkol26** [comment]
Yes, sounds like the same issue.

**Comment by pre** [comment]
closins in favor of #698
