### ISSUE TITLE
iOS builds' compile errors are no longer reported to the user

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#735]
Compile error will only raise “Compile error which was possibly caused by one of the Cordova plugins defined for this application. You can try compiling this plugin on your machine using XCode and vanilla Cordova to debug and fix the error.”

The actual error message is not displayed anymore.

**Comment by bFlood** [comment]
+1 - there's no log file either

**Comment by bFlood** [comment]
anything on this? I can't compile a custom scanner for ios

**Comment by pre** [comment]
Compile error logs are now delivered again for iOS builds. Sorry for the inconvenience.

**Comment by pre** [comment]
This was now a workaround; Builds with compile errors have a delay before the build is reported back to the user. The proper fix would be to fail without delay AND deliver the error log to the user. Currently it's either way but not both. :P

**Comment by bFlood** [comment]
thanks petrus

any idea what this build error means?

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MainViewController", referenced from:
      l_OBJC_$_CATEGORY_MainViewController_$_CDVViewController in PluginUtil.o
      anon in PluginUtil.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Release-iphoneos/Build/Products/Release-iphoneos/SDL_Mobile_Scanner.app/SDL_Mobile_Scanner normal armv7
(1 failure)

**Comment by pre** [comment]
AppGyver Wrapper does not have a MainViewController which your code refers to. Your plugin should use the Cordova Plugin Interface's method to acquire the reference to the ViewController ( or WebView) instead of accessing the class directly (ie. not respecting the interface defined by Cordova).
