### ISSUE TITLE
postMessage bug

### ISSUE THREAD

**Issue by aromanyuk** [AppGyver/steroids#736]
when i sending simple post message(or by supersonic channel) to other view i have:
```javascript
$scope.oauth = function (provider) {
            socialAuth(provider, function (obj, user) {
                switch (obj.status) {
                    case 200:
                        var message = {
                            recipient: "form_type_change",
                            message: "test"
                        };
                        window.postMessage(message);
```

Uncaught TypeError: Cannot read property 'channel' of null supersonic.js:25338

the line in supersonic code is 
```javascript
return (event.data.channel === channelName) && !deepEqual(event.data.sender, receiver);
```

from
```javascript
inboundStream = function(channelName, receiver) {
    return Bacon.fromEventTarget(window, "message").filter(function(event) {
      return (event.data.channel === channelName) && !deepEqual(event.data.sender, receiver);
    }).map(function(event) {
      return event.data.message;
    });
  };
```

**Comment by aromanyuk** [comment]
on webview scanner

**Comment by pre** [comment]
Which Android OS version you have tried with? 

Behaviour of the Android WebView is dependent on Android OS version. Android OS prior to 4.4 uses internally WebKit, Android 4.4+ uses Chromium.

**Comment by pre** [comment]
@aromanyuk What did you do to get the issue solved? It would be valuable for other people who might encounter the same problem. Thanks!

**Comment by aetchegoyen** [comment]
@aromanyuk  I'm having the same issue, how did you solve it?

**Comment by devtim123** [comment]
i have also the problem using the scanner and android version 4.4.4. Also notice that a crosswalk build do not have this problem.

there is my error message: Uncaught TypeError: Cannot read property 'channel' of null | supersonic.js:22340

this occurs when app starts and my app doesnt work after this error appears.

any help please?

**Comment by harsaharsa** [comment]
I'll have the person who built the Supersonic postMessage channel take a look early next week. Does the error occur immediately when the WebView is opened, or do you execute some code first?
