### ISSUE TITLE
steroids connect loads fixed versions for angular etc.

### ISSUE THREAD

**Issue by gehirnstuerm** [AppGyver/steroids#746]
The steroids connect node_module loads its own versions for:
angular
angular-bootstrap
angular-qrcode
angular-ui-router
bootstrap
jquery
lodash
qrcode-generator
restangular

Using these in the steroids project fails to load the project files because they seem already been served by localhost. Maybe change the steroids-connect structure?

**Comment by harsaharsa** [comment]
This will be fixed in 4.0.8!

**Comment by pre** [comment]
4.0.8 is out
