### ISSUE TITLE
Does Android navigation bar include status bar?

### ISSUE THREAD

**Issue by rclai** [AppGyver/steroids#754]
I'm on an LG G3 and when I look at the SS initial app, the navigation bar color (the initial light blue) stops just below the status bar, is it supposed to be like that?

I noticed that on iOS, the color extends all the way to the status bar.

**Comment by harsaharsa** [comment]
That's how Android is laid out – if you look at other native apps, the status bar is consistently black and any content, including a navigation bar stops below it.

**Comment by rclai** [comment]
Ok cool, thanks.
