### ISSUE TITLE
Android system "backbutton" closing app

### ISSUE THREAD

**Issue by aromanyuk** [AppGyver/steroids#759]
Android 4.4.4, Build 4.0.4-edge3
Tap on "backbutton" in Adroid closing(exit) app. Need some method to prevent this action and have possibility to ask user before close app or simple prevent this action if layer stack have only one item.

**Comment by harsaharsa** [comment]
You can use the `supersonic.device.buttons.back.whenPressed` event listener:

http://docs.appgyver.com/supersonic/api-reference/stable/supersonic/device/buttons/back/whenpressed/
