### ISSUE TITLE
super-navigate does not work consistently between AdHoc and Scanner builds

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#770]
From https://forums.appgyver.com/#!/steroids:view-id-not-working-adhoc

![view-id not working adhoc build appgyver x](https://cloud.githubusercontent.com/assets/63895/5813704/8d0573f2-a08a-11e4-8a4d-17f45c8d980d.jpg)

**Comment by harsaharsa** [comment]
Judging from the error message, this issue is likely caused by trying to push the same preloaded view twice. Closing until proper repro.
