### ISSUE TITLE
[Android] Some webViews only works after page reload

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#771]
Same code works fine on iOS; on Android however, sometimes the webView only works when i reload the page from Chrome debugger. Initially it displays a blank page....

**Comment by pre** [comment]
Could you elaborate on the conditions when this happens?

eg. have you seen this with
- `layers.push()`
- `modal.show()`

Does this happen only in Crosswalk Scanner ?

**Comment by fidoboy** [comment]
It happens both on scanner and adhoc build. I'm pushing a steroids webView using the push method. Also using angular, not sure if it's related.

**Comment by pre** [comment]
Have you experienced it only with Crosswalk?

**Comment by fidoboy** [comment]
Yes, crosswalk only

**Comment by fidoboy** [comment]
However I must add that i've not tested without crosswalk, so not sure if it happens the same or not

**Comment by fidoboy** [comment]
This was related to this issue: https://github.com/AppGyver/steroids/issues/772 and it's solved right now, so I'll close this issue :)
