### ISSUE TITLE
Enable app test on desktop browser - problem with AngularJs version

### ISSUE THREAD

**Issue by andre-luis** [AppGyver/steroids#777]
I'm developing a SPA and I would like to be able to test my app on my desktop browser. Even with the improvement Steroids brings to the table when it comes to upload, view and debug the app on a mobile device, it is faster still to do it on the desktop browser. I have seen that I can access the app in my desktop browser through http://localhost:4567/... but, the AngularJs version available there is not the one I set on my files. The angular I'm working with is 1.3.10 and the angular I'm getting from http://localhost:4567/ is - oddly - 1.2.27. As I'm using angular-route - and for that component the version available is the one I set (the same as the angular version) - the very basic ng-view directive does not work. Well it is a very strange issue, and it seems, at first, something easy to fix... On my mobile everyting works fine, since I'm getting the right version of angular there.

**Comment by pre** [comment]
It might be faster to develop on the desktop browser, until you want to use the native features which are only available in the device (or simulator). 

We used to have an experimental WebBridge which imitated eg. Tab Bar with a set of iframes. That didn't work in the end so we dropped support for that.

In case you have found a bug, please clarify your issue with the problem details and how it affects the project which is executed on the device / simulator. The current problem description is too vague.

**Comment by pre** [comment]
PS You might have experienced this issue: https://github.com/AppGyver/steroids/issues/746 -- it's now fixed.
