### ISSUE TITLE
supersonic.ui.navigationBar.hide() Not working on Andriod

### ISSUE THREAD

**Issue by vrfurl** [AppGyver/steroids#784]
Hi,

From the example app I modified the settings controller as follows:

angular
  .module('example')
  .controller('SettingsController', function($scope, supersonic) {
    $scope.navbarTitle = "Settings";

        supersonic.ui.navigationBar.hide();

    });

Adding only the hide() call.

On my Iphone the Navbar is hidden as expected however in all three of my Android devices the calls have no effect on the Navbar.

**Comment by battmanz** [comment]
I'm seeing the same error on my Android phone and the Genymotion emulator. Also I've noticed that the navigation bar is always shown even if I remove the `<super-navbar>` element (as well as its children).

**Comment by neophob** [comment]
+1

**Comment by harsaharsa** [comment]
I'm not able to replicate this, navigation bar (though not the black status/notification center bar) hides correctly with the API call. Can you provide a simple repro app e.g. as a GitHub repository where this happens?

**Comment by djuric42** [comment]
@harsaharsa I think that problem appears when page is preloaded (structure.coffee file)

**Comment by devtim123** [comment]
+1
yes this happens if you preload the webview in the structure.coffee. any suggestions to solve this problem? i need the webview to be preloaded but i dont want any navbar. only if i pop the webview with no navbar, then the navbar should come back, but this does not seem to work.

**Comment by harsaharsa** [comment]
Does the preloaded WebView have a `<super-navbar>` element?

**Comment by devtim123** [comment]
no it has not. also the WebViews with NavBar don't have a <super-navbar> element. maybe thats the problem?

**Comment by aliyazdani** [comment]
+1
happens on android. Not preloading the view.  Running the hide() function in browser console works but not in controller.

**Comment by harsaharsa** [comment]
This should be now fixed with Android nativ runtime v4.0.5, please update your scanner and let me know if it still perisist! If it does, I'll reopen the issue.

**Comment by sunny061** [comment]
I am facing the same issue. I pushed a view using supersonic.ui.layers.push(view) and it automatically creates a navbar with a back button. I want to hide that navbar but supersonic.ui.navigationBar.hide() is not working on android.

**Comment by harsaharsa** [comment]
@sunny061 please post your issue with example code to http://community.appgyver.com – this sounds like a separate issue from this one, and more people will be available to help you on the forums. :)

**Comment by marcussaad** [comment]
@sunny061, were you able to fix this? I'm facing the same issue using ```.layers.push(view)``` on Android. 
```navigationBar.hide()``` is doing nothing.

**Comment by sunny061** [comment]
@marcussaad Try wrapping the code around this...

supersonic.device.ready.then( function() {
  //add your navigationbar hide code here
});
