### ISSUE TITLE
NavigationBarButton Not Working Properly.

### ISSUE THREAD

**Issue by vrfurl** [AppGyver/steroids#804]
Hi

The NavigationBarButton does not appear to be working properly.

invoking the following code in my Controller I'm observing the following:

```

    var rightButton = new supersonic.ui.NavigationBarButton({
            title:"test2",
            onTap: function() {
                 alert("I've been tapped");
            }
        });

        options = {
            buttons: {
                right: [rightButton]
            }
        }
        supersonic.ui.navigationBar.update(options);
```

In Andriod:
The button gets added to the right side of the NavigationBar however the onTap function does not appear to be called.

In IOS:
The button is not added to the NavigationBar or is not visible anywhere.

Thanks for having a look.

**Comment by harsaharsa** [comment]
We haven't been able to replicate this – all our internal code for using navigation bar buttons works great. Closing as a faulty JS issue.
