### ISSUE TITLE
steroids.app.absolutePath doesn't work in read-only on Android adhoc

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#805]
Looking at this table: http://docs.appgyver.com/tooling/wrapper/android/android-feature-table/ it says that crosswalk adhoc build should work in read-only mode with `steroids.app.absolutePath` however when I try to use it to pass a file url to a custom plugin it doesn't work. It works fine on scanner build.

**Comment by pre** [comment]
Cordova File plugin cannot access Android assets (the read-only location where application files are stored in non-Scanner builds). This is an issue with the Cordova File plugin, so I'll close this issue. 

Thanks for pointing out that this should be clarified in that document, this is now documented.

**Comment by fidoboy** [comment]
Well, now it explains that files can be headed using ```http://localhost``` but it doesn't seems to work. Can't access the files using the http protocol from my cordova plugin, it doesn't work

**Comment by pre** [comment]
That's true. `http://localhost` is intercepted by the WebView, there's no real local webserver. Therefore your Cordova plugin doesn't know anything about it. 

For Cordova plugins you must access the filesystem directly:
- `steroids.app.absolutePath` = location of your application (read-only on standalone)
- `steroids.app.absoluteUserFilesPath` = writable location for user supplied content

**Comment by fidoboy** [comment]
Just for the record, you should add that ```steroids.app.absolutePath``` only works on iOS, because when using Android that location can't be accessed/readed from Cordova plugins (like the file plugin or low latency audio plugin). As we discussed in other thread (can't locate it right now, sorry), the workaround I'm using is to copy the files (using a secret feature on application.coffee) to absoluteUserFilesPath location and then use them from there.

**Comment by pre** [comment]
Thanks for the clarification. :)
