### ISSUE TITLE
Window dimensions on Android not working on DOM ready

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#807]
I've noticed that `window.innerHeight` or `window.innerWidth` doesn't work on Android on document ready event. This works fine on iOS platform. The weird thing is the same code, works on Android if I replace the center view from drawer, but it doesn't work when i push the same webView into the stack. This sounds like a bug, but while it's being solved, there is any workaround to get the window dimensions from javascript? I want to mean the available space, that is, screen height minus the navigation bar height.

thanks in advance,

**Comment by pre** [comment]
Is this with the platform WebView or using Crosswalk?

Remember that the behavior of the platform WebView depends highly on the Android OS version. Platform WebView with Android <= 4.4 is practically unusable.

**Comment by fidoboy** [comment]
This is crosswalk

**Comment by harsaharsa** [comment]
https://github.com/AppGyver/steroids-repro-template/tree/inner-width-repro – seems like they are calculated correctly after the `DOMContentLoaded` event, as expected. Please respond with a forked repro if this is still an issue, otherwise closing it.

**Comment by fidoboy** [comment]
I've just tested your repro and also it works for me, however doing the same on my code, with same DOMContentLoaded **BEFORE** loading Cordova and Steroids does not work (I was using angular element document ready initially). This leads me to think that it happens when there is more than one webView or when the webView is being pushed from other. In all cases works on iOS flawlessly, but it fails on Android in my project :(

**Comment by fidoboy** [comment]
May be this gives you some clue about what is happening: when I reload the document (using the chrome remote inspector) it works fine...

**Comment by fidoboy** [comment]
It seems that this bug is something like the 'deviceready' problem solved with last release; may be you should try with a more complex project and loading more assets. As I've said, your repro works fine for me but if i use the same code in my project it fails. It could be very helpful if @sebmartel , @mmerkes , @poppahorse or any other steroids user, test this on their projects; it's as simple as putting a ```steroids.logger.log``` with ```window.innerHeight```inside (or may be an alert()) and see if it works (from the DOMContentLoaded event or document ready). I'm almost sure that there is a Steroids bug with this. Also any suggestion about a workaround could help; but i can't imagine any other way to know the available screen dimensions (unfortunately, using ```screen.height``` you'll get the size without taking navigation bar in consideration)

**Comment by fidoboy** [comment]
Ok, i've found the source of this bug. Problem is with loading screen on Android, you can't get the window dimensions until the loading screen has been removed; that's why the @harsaharsa example worked fine but it doesn't work in my app. If there is no loading screen or you remove it **before** getting the ```window.innerHeight```value, then it works fine, **BUT** if you try to get this value when loading screen is being displayed, then returned value is always 0 even if DOM is ready event has been triggered in your new webView. I bet that this is how Crosswalk works and if a webView is not visible, you can't get the right values. 

Knowing this, now I can use a dirty workaround in my project or may be that there is any way that Steroids native part injects the values into the window object to avoid these kind of problems. What do you think? Could we consider this as a bug or it's just a platform limitation? Any info or tip about the issue is more than welcome...

Also, please, consider adding this info (if confirmed) into the Steroids and Supersonic documentation to avoid headaches to other users :smile:

**Comment by harsaharsa** [comment]
@fidoboy thanks again for the detective work! I created a new issue at https://github.com/AppGyver/steroids/issues/869
