### ISSUE TITLE
url Steroids Connect Screen not work with OSX 10.10.2

### ISSUE THREAD

**Issue by eduardovrocha** [AppGyver/steroids#808]
http://localhost:4567/__connect/connect.html?qrcode=appgyver%3A%2F%2F%3Fips%3D%255B%2522127.0.0.1%2522%252C%2522192.168.0.13%2522%255D%26port%3D4567

**Comment by eduardovrocha** [comment]
Error code: ERR_CONNECTION_REFUSED

**Comment by pre** [comment]
Do you have Steroids CLI running?

**Comment by eduardovrocha** [comment]
i get worked now .. but i'm still having a problem, but this time is about to connect my application on appgyver to my back end. I'm using Rails also i got my api to json. I like to know if i get PREMIUM SUPPORT ten i will have custom support for this issue

**Comment by pre** [comment]
I'll close this issue since this is not a bug report.

Please send email to contact@appgyver.com if you want to inquire about premium support. Thanks!
