### ISSUE TITLE
Safari Debugger fails to run

### ISSUE THREAD

**Issue by har96** [AppGyver/steroids#809]
When running steroids connect, I tried to open the safari debugger with the `sd` command.  Safari did indeed open, but before steroids could get a list of view addresses for me to select from, steroids raised the error:
`ERROR: Error on line 246: TypeError: undefined is not an object (evaluating 'menu.getMenuItems') (0)`
After raising the Error steroids returned to regular execution by bringing up the next command prompt.  Safari remained open.

This could very well have something to do with the fact that I recently updated Safari to the latest version (v8.0.2; I am running OS X 10.10.1) although I do not know for sure, as I never tried to run `sd` on the older version.

**Comment by pre** [comment]
1) Have you enabled the Safari Developer menu? 

2) Are you using a Debug Scanner which you have built from [the Build Service](https://cloud.appgyver.com) ?

**Comment by har96** [comment]
Ah, my bad.  I should have thought of that.  Once I enabled develop in the Safari preferences it works.  Thanks!

**Comment by pre** [comment]
Thanks! We'll need to provide a human readable error for the case where Developer menu has not been enabled.
