### ISSUE TITLE
Facebook feature url gives 404

### ISSUE THREAD

**Issue by kevinsimper** [AppGyver/steroids#813]
https://github.com/AppGyver/steroids/blob/6699fa7e199ccd8bd9882e94ac155960dfb65617/src/steroids/ConfigJsonGenerator.coffee#L42

Where is the correct urls?

**Comment by harsaharsa** [comment]
That's an XML namespace, not a proper URL. It's not meant to point to a real website, though I can see the confusion. Closing this, in any case.
