### ISSUE TITLE
New install, steroids connect problem

### ISSUE THREAD

**Issue by mkoivuporras** [AppGyver/steroids#814]
I have a new install, everything in the install phase went ok. OSX Yosemite 10.10.1, Steroids 4.0.8, NPM 2.5.1, Node 0.12.0, Git 1.9.3

I'm trying the first mile in tutorials, but steroids connect fails:

8 Feb 22:45:23 – The server has now been started on port 4567
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/markokoivuporras/.node-gyp/0.12.0/src/nodeobjectwrap.h, line 77.
Abort trap: 6

Any help on that?

**Comment by pre** [comment]
No idea. Could you try if using a custom node version with [NVM](https://github.com/creationix/nvm) would help?

**Comment by JWPersh** [comment]
Anyone find a reason or fix for this issue? I have the exact same one.

Done, without errors.
16 Feb 11:32:37 - The server has now been started on port 4567
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /usr/local/lib/node_modules/steroids/node_modules/chokidar/node_modules/fsevents/.node-gyp/0.12.0/src/node_object_wrap.h, line 77.
Abort trap: 6

**Comment by pre** [comment]
@JWPersh You're using a system wide node installation. Could you try with NVM?

I personally consider system-wide node installation very inflexible (you need to mess around with sudo etc). NVM fixes all that, and with NVM you can easily have the newest Node version too.

**Comment by JWPersh** [comment]
@pre Thanks, great advice :)

Its all working great and also took a nice detour into learning more about NVM!

**Comment by pre** [comment]
Good to hear! :)
