### ISSUE TITLE
Data doesn't work anymore

### ISSUE THREAD

**Issue by tjvanderende** [AppGyver/steroids#819]
Appgyver…
Suddenly all my apps using the new data structure of supersonic in connect panel are unable to be used, says application can't be found when I try to make a test row inside browse data tab.
And new apps show in the chrome webinspector:
OPTIONS rest-api.appgyver.com/v2//recentpost net::ERRNAMENOT_RESOLVED
Come on.. this are production apps, has there been a update or something? Or do I miss something?
This is just a scaffold I generated. Should work right?
Please help.
Gr Tjibbe

**Comment by pre** [comment]
Main issue https://github.com/AppGyver/steroids/issues/823

**Comment by harsaharsa** [comment]
Closing this as no further replies here – follow #823 for updates.
