### ISSUE TITLE
Large delay in rendering content?

### ISSUE THREAD

**Issue by poppahorse** [AppGyver/steroids#822]
When I load a view, there seems to be a large delay (2-5 seconds) between when the load spinner finishes, and the content loading. The content doesn't render and the page is just blank in this time.

I set `$scope.showSpinner = true;` then make a Restangular call (using a rest client, these take 200ms ish), and on complete set `$scope.showSpinner = false;`

This happens on all views.

Interestingly, when I refresh a views data when that view is visible, the spinner seems to behave properly, so the delay seems to be in loading the content initially into $scope.

Also suffering from deviceready will no fire issues, so unsure if related

**Comment by pre** [comment]
Main issue https://github.com/AppGyver/steroids/issues/823

**Comment by poppahorse** [comment]
thanks. unsure if still applies to me though as I am using my own REST api via restangular

**Comment by pre** [comment]
It applies if you're using Supersonic Data. Effort is being made to speed it up, though.

**Comment by harsaharsa** [comment]
Is the same Angular code fast in a browser?

**Comment by poppahorse** [comment]
@harsaharsa yes, virtually instant in browser

**Comment by harsaharsa** [comment]
Right, I read the description wrong – the problem is not tied to the Angular code, but ratrher https://github.com/AppGyver/steroids/issues/830

Closing this as duplicate unless further evidence comes up that it's a separate issue.
