### ISSUE TITLE
Build Service should return a user-friendly filename instead of application.apk / application.ipa

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#828]

**Comment by poppahorse** [comment]
I have been manually renaming them to name-buildtype-buildid.apk/ipa, so if it could do this or something similar that would be awesome!

**Comment by aetchegoyen** [comment]
It could be something like [appName]-build.apk/ipa

**Comment by poppahorse** [comment]
definitely need the build type in there. if you have a directory full of builds, just the build id alone wont be enough without having the build history alongside it to cross reference with

**Comment by Leeds-eBooks** [comment]
:+1:

**Comment by realpasro09** [comment]
totally agreed, could be nice If I can put the name before download it, or at least add the # of the build.

**Comment by bFlood** [comment]
+1

**Comment by poppahorse** [comment]
Any news on this guys? Been absent for a few months, and was super hoping this had been improved :)

**Comment by poppahorse** [comment]
@pre @harsaharsa ?

**Comment by harsaharsa** [comment]
Sorry, no updas. :( It's a very small fix, which makes it doubly annoying to not be able to implement it, but there's a lot of those, so this has been consistently pushed back in the backlog. We're working hard to get everything in the platform aligned and in focus, but for now, it doesn't look like this is receiving love soon.

**Comment by poppahorse** [comment]
:( thanks for the update

don't want to sound salty, but when will we get some commitment to fixing these issues (some little, some fairly major) of which as you point out, there are many?

**Comment by pre** [comment]
Build Service now returns a human friendly filename. We're focusing heavily on the Composer2 platform at the moment. Thank you for understanding. 

:)

**Comment by poppahorse** [comment]
Its like christmas :D thanks guys!

Looking forward to Composer 2 being more polished so we can get some more of this sweet sweet lovin :heart_eyes:

**Comment by poppahorse** [comment]
FYI didnt see this notification, I actually saw the filename fixed in the wild... today was a good day
