### ISSUE TITLE
Unknown Provider: supersonic provider

### ISSUE THREAD

**Issue by Rajan** [AppGyver/steroids#829]
I'm adding the module ngTouch and facing this issue.

"Error: [$injector:unpr] Unknown provider: supersonicProvider <- supersonic <- LearnMoreController
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=supersonicProvider%20%3C-%20supersonic%20%3C-%20LearnMoreController
minErr/<@http://localhost:4567/components/angular/angular.js:63:12
createInjector/providerCache.$injector<@http://localhost:4567/components/angular/angular.js:3997:19
getService@http://localhost:4567/components/angular/angular.js:4144:39
createInjector/instanceCache.$injector<@http://localhost:4567/components/angular/angular.js:4002:28
getService@http://localhost:4567/components/angular/angular.js:4144:39
invoke@http://localhost:4567/components/angular/angular.js:4176:1
$ControllerProvider/this.$get</</<@http://localhost:4567/components/angular/angular.js:8454:11
nodeLinkFn/<@http://localhost:4567/components/angular/angular.js:7700:13
forEach@http://localhost:4567/components/angular/angular.js:331:11
nodeLinkFn@http://localhost:4567/components/angular/angular.js:7699:11
compositeLinkFn@http://localhost:4567/components/angular/angular.js:7078:13
compositeLinkFn@http://localhost:4567/components/angular/angular.js:7081:13
publicLinkFn@http://localhost:4567/components/angular/angular.js:6957:30
bootstrapApply/<@http://localhost:4567/components/angular/angular.js:1450:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:4567/components/angular/angular.js:14401:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:4567/components/angular/angular.js:14500:18
bootstrapApply@http://localhost:4567/components/angular/angular.js:1448:9
invoke@http://localhost:4567/components/angular/angular.js:4185:14
bootstrap/doBootstrap@http://localhost:4567/components/angular/angular.js:1446:1
bootstrap@http://localhost:4567/components/angular/angular.js:1466:1
angularInit@http://localhost:4567/components/angular/angular.js:1360:5
@http://localhost:4567/components/angular/angular.js:26125:5
trigger@http://localhost:4567/components/angular/angular.js:2744:7
createEventHandler/eventHandler@http://localhost:4567/components/angular/angular.js:3014:9

**Comment by Rajan** [comment]
This was solved with adding a line like this.

<script src="/components/supersonic/supersonic.js"></script>

**Comment by justincolangelo** [comment]
I don't see the line you added.

**Comment by sunny061** [comment]
Facing a similar issue. @Rajan, where is the line?
