### ISSUE TITLE
Paid option for faster builds

### ISSUE THREAD

**Issue by hir3npatel** [AppGyver/steroids#835]
Would be useful if there were a paid account option to speed up build time, avoid having to wait in the queue and instead have your builds kicked off immediately.

**Comment by kaoskeya** [comment]
+1

**Comment by harsaharsa** [comment]
Thanks for the suggestion! We have some premium stuff in the works, stay tuned. :)

**Comment by albertwchang** [comment]
Curious if the premium stuff will be lumped within the "add-on" category?  I am currently a paid subscriber of the add-on service and will continue to do so if the premium stuff is included

**Comment by albertwchang** [comment]
Curious if the premium stuff will be lumped within the "add-on" category?  I am currently a paid subscriber of the add-on service and will continue to do so if the premium stuff is included
