### ISSUE TITLE
Update chokidar version

### ISSUE THREAD

**Issue by polysics** [AppGyver/steroids#837]
To avoid an issue on OSX Yosemite where `fsevents` 0.3.0 fails to install, the `chokidar` package needs to be updated. I tried with the current 1.0.0-rc3 without issues, but there might be an earlier release that still loads the correct version.

**Comment by harsaharsa** [comment]
Thanks for the heads-up! We'll be sure to update this. Can you give more specific conditions when the `fsevents` fails to install – we're successfully running Steroids CLI on several Yosemite Macs without a hitch.

**Comment by polysics** [comment]
I am using NVM with version v0.10.36, on a fresh installation. XCode CLI tools are up to date.

**Comment by harsaharsa** [comment]
Chokidar is now updated to 1.0.0-rc3 with the latest CLI release (4.0.12), can you verify the fix works?
