### ISSUE TITLE
Navigation bar title gets misaligned when only the right menu button is set

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#843]

**Comment by Gniller** [comment]
For Android, the same thing happens when only the left menu button is set. For IOS this is not the case.

**Comment by walle** [comment]
A quick and dirty fix for this is to add a empty button on the opposite side eg. if we have a back button

```js
var emptyButton = new steroids.buttons.NavigationBarButton();
steroids.view.navigationBar.setButtons({
  right: [emptyButton]
});
```

Do you think the fix for this issue will break this "hack"?

**Comment by pentateu** [comment]
Android layout managers are not up to the task.. so we have used a frameLayout with 3 LinearLayouts on top of it: 1 for the left buttons.. oner for the right buttons and one for the title (text and image) .
This way the title is always centred and is not affected by the buttons. The downside is that if you use too many buttons they can overlap with title...  so it is up to the developer to be smart about the number and size of buttons used ;-)  this fix is coming soon in the next android edge build.

**Comment by RWOverdijk** [comment]
It also seems that the "back" button doesn't quite fit. If I name it "Terug" (Dutch for "Back") the arrow doesn't show and the top left of the T sticks out of view. IS this related?
