### ISSUE TITLE
Couchbase lite plugin won't build on Android 

### ISSUE THREAD

**Issue by sandersoeteman** [AppGyver/steroids#844]
It looks like Couchbase lite has a few dependencies in common with the Android scanner I'm trying to build. I get “duplicate file” errors for the following files:

jackson-core-asl-1.9.2.jar
jackson-mapper-asl-1.9.2.jar

When I include these in my plugin, the build fails, resulting in error message 1 (below).
When I remove these .jar files from my plugin and plugin.config, the build succeeds, but when I try to run the scanner, te scanner crashes. When I look at the crash logcat, I see it was trying to load a object which was not included in the scanner (error message 2 (below)).
How do I make sure these jars are included in my scanner, but don't cause a duplicate file error?

Thanks,

Sander

<<<<<ERRORMESSAGE 1>>>>>>>
:runtimes:ScannerChromium:dexArmandx86Debug
:runtimes:ScannerChromium:processArmandx86DebugJavaRes UP-TO-DATE
:runtimes:ScannerChromium:validateDebugSigning
:runtimes:ScannerChromium:packageArmandx86DebugError: duplicate files during packaging of APK /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromi um/build/outputs/apk/ScannerChromium-armandx86-debug-unaligned.apk
Path in archive: META-INF/ASL2.0
Origin 1: /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromi um/buil//intermediates/exploded-aar/client.modules/AGCordova/unspecified/libs/jackson-core-asl-1.9.2.jar
Origin 2: /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromi um/build/intermediates/exploded-aar/client.modules/AGCordova/unspecified/libs/jackson-mapper-asl-1.9.2.jar
You can ignore those files in your build.gradle:
android {
packagingOptions {
exclude ‘META-INF/ASL2.0’
}
}
FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ‘:runtimes:ScannerChromium:packageArmandx86Debug’.
    Duplicate files copied in APK META-INF/ASL2.0
File 1: /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromi um/build/intermediates/exploded-aar/client.modules/AGCordova/unspecified/libs/jackson-core-asl-1.9.2.jar
File 2: /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromi um/build/intermediates/exploded-aar/client.modules/AGCordova/unspecified/libs/jackson-core-asl-1.9.2.jar

<<<<<ERRORMESSAGE 2>>>>>>>
D/AndroidRuntime( 2178): Shutting down VM
W/dalvikvm( 2178): threadid=1: thread exiting with uncaught exception (group=0xa4d88b20)
E/AndroidRuntime( 2178): FATAL EXCEPTION: main
E/AndroidRuntime( 2178): Process: net.pictoplanner.android.pictoplanner_s, PID: 2178
E/AndroidRuntime( 2178): java.lang.NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper

Steps to reproduce: clone the couchbase lite plugin and remove the commons-io-2.0.1.jar from the lib folder and its reference from the plugin.xml. 

Could you please look into this? I'm really stuck here!

**Comment by pre** [comment]
You have two JAR files which both try to include  a file called `META-INF/ASL2.0`. This leads into a conflict and Gradle refuses to build it. 

I ignored this file for you. Please try building with Android 4.0.5-edge6-jackson-test. You can find it on the bottom of "Show older versions" in the Build Service's Android tab.

**Comment by sandersoeteman** [comment]
This doesn't lead to the same error, so seems to be working. Thanks! I get another error now, but will open another issue for that
