### ISSUE TITLE
How to download the build from cloud

### ISSUE THREAD

**Issue by talvinder** [AppGyver/steroids#846]
Due to a hard disk crash, I lost my code base on localhost. But my app is available on appgyver cloud and I can use scanner to browse the app.

So, is there a way to download my app from appgyver's cloud?

**Comment by pre** [comment]
Email contact@appgyver.com and we can help you after we have verified your identity.

Please start using Github so that this won't happen to you again.

**Comment by talvinder** [comment]
Thanks!
I use bitbucket and was able to recover from there successfully. 


Sent from Outlook




On Mon, Mar 2, 2015 at 3:23 AM -0800, "Petrus Repo" <notifications@github.com> wrote:












Email contact@appgyver.com and we can help you after we have verified your identity.



Please start using Github so that this won't happen to you again.
