### ISSUE TITLE
Android custom URL scheme not working.

### ISSUE THREAD

**Issue by manujbahl** [AppGyver/steroids#859]
Im using 4.0.4 for Android and this doesn't seem to work for me on a custom scanner build.
Can someone confirm that it works. I setup a custom url on the build settings in the Custom protocols.
When i write myappname:// on chrome it doesn't switch to the app and gives a google search error.

**Comment by manujbahl** [comment]
Any word guys ...

**Comment by mmelkko** [comment]
Please test custom URL scheme by using either the `openURL` method in your Steroids/Supersonic app or clicking a link on a web page that uses the custom url in a link. Writing the custom url into Chrome's address bar is not supposed to open the app, only a link to the URL opens it.

I tested and custom URL schemes worked fine in 4.0.5-edge6 when triggered with `openURL`. Closing issue unless you can confirm with a repro that openURL or a link from a webpage/email does not open your app.

**Comment by harsaharsa** [comment]
See also https://github.com/AppGyver/steroids/issues/861 for a related issue!
