### ISSUE TITLE
Opening an already-running app via a custom URL scheme link freezes the app

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#861]
Closed apps can be opened fine via a custom URL scheme link, but if the app is running, it will freeze.

See also https://github.com/AppGyver/steroids/issues/865 for a related issue.

Previous ticket was #141 which I'll leave as closed because it was about a different issue.

**Comment by harsaharsa** [comment]
A fix is live with version [4.0.5-edge8](https://github.com/AppGyver/scanner/blob/master/changelog-android-fresh-edge.md#405-edge8-2015-03-11), available from the build service. Please test!

**Comment by sebmartel** [comment]
I'll give a try, is there a similar fix for iOS?

**Comment by harsaharsa** [comment]
I wasn't aware of a similar problem with iOS. Are you experiencing this behavior on iOS too?

**Comment by manujbahl** [comment]
We still seem to have some issues here. We have 2 listeners hooked up for the phase and resume events and after edge8(& onwards) we only get notifications on one of the listeners. the second listeners does not get notified. Is there any change int eh pub sub model that would affect that behavior ?

**Comment by manujbahl** [comment]
Hey Harri…

The fix does not completely work I have updated the issues with my latest observations on iOS and Android.

https://github.com/AppGyver/steroids/issues/861 <https://github.com/AppGyver/steroids/issues/861>
https://github.com/AppGyver/steroids/issues/862 <https://github.com/AppGyver/steroids/issues/862>

Can you guys please take a look.

Thanks
Manuj

**Comment by harsaharsa** [comment]
What do you mean with "phase" event? What type of navigation stack structure you have when you're getting the error?

**Comment by manujbahl** [comment]
Sorry I meant pause event.. That maybe an issue on our side (we may not have structured it right).
However on Android I still see that the launch url is empty when the resume event is called.

Our code is structured in the following way ..  

 ionic.Platform.ready(function() {

   // THIS IS FOR COLD START OF THE APP
   $scope.checkAndHandleLaunchURL();

    $ionicPlatform.on('pause', function () {
    }, false);
    
    $ionicPlatform.on('resume', function () {
      console.log('got resume');
      // THIS IS FOR WHEN THE APP WAS IN BACKGROUND
      $scope.checkAndHandleLaunchURL();
    }, false);
  });

  $scope.checkAndHandleLaunchURL = function () {
    var launchURL = steroids.app.getLaunchURL();
    console.log('launchURL = ' + launchURL);
  };


Here are the console outputs from cold start and background resume scenarios
using the myawesomeapp://main/invite  link from an email.


COLD START 
got resume 
got resume -  on to checkAndHandleLaunchURL 
launchURL = myawesomeapp://main/invite 


APP IN BACKGROUND
got resume
got resume -  on to checkAndHandleLaunchURL 
launchURL =  

Can you confirm if there is an issue configuring the launchurl for android for resume scenario.
The same scenario works fine on iOS.

**Comment by manujbahl** [comment]
Sorry I meant pause event.. That maybe an issue on our side (we may not have structured it right).
However on Android I still see that the launch url is empty when the resume event is called.

Our code is structured in the following way .. 

ionic.Platform.ready(function() {
	// THIS IS FOR COLD START OF THE APP
	$scope.checkAndHandleLaunchURL();

	$ionicPlatform.on('pause', function () {
	}, false);

	$ionicPlatform.on('resume', function () {
		console.log('got resume');
		// THIS IS FOR WHEN THE APP WAS IN BACKGROUND
		$scope.checkAndHandleLaunchURL();
	}, false);
});

$scope.checkAndHandleLaunchURL = function () {
	var launchURL = steroids.app.getLaunchURL();
	console.log('launchURL = ' + launchURL);
};


Here are the console outputs from cold start and background resume scenarios
using the myawesomeapp://main/invite link from an email.

COLD START 
got resume 
got resume - on to checkAndHandleLaunchURL 
launchURL = myawesomeapp://main/invite 

APP IN BACKGROUND
got resume
got resume - on to checkAndHandleLaunchURL 
launchURL = 

Can you confirm if there is an issue configuring the launchurl for android for resume scenario.
The same scenario works fine on iOS.

**Comment by harsaharsa** [comment]
Yes, that's currently still a bug, see https://github.com/AppGyver/steroids/issues/865 – let's follow up in the other issue about this!

**Comment by harsaharsa** [comment]
Fixed in Android 4.0.5!

**Comment by watzenare** [comment]
Hi,
I've been searching how to ask the user to open a link using my app that is made with AppGyver and I don't know how can I do it. Can I find some documentation about how to make my application default with my links?

Thank you!

**Comment by Leeds-eBooks** [comment]
@watzenare http://docs.appgyver.com/supersonic/guides/navigation/navigating-between-apps/communicating-with-external-apps/

**Comment by watzenare** [comment]
Thank you @Leeds-eBooks !
