### ISSUE TITLE
Changing an SVG tab bar item's size on Android doesn't work as intended

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#867]
tab-bar-item#settings {
  background-image: url(icons/cog.svg);
  background-size: 100;
}

On iOS, setting the `background-size` changes the size of the icon displayed.
On Android, it just scales the image and then makes it take up the whole space, leading to blurred images.

![img_0023](https://cloud.githubusercontent.com/assets/1327592/6618981/a5923cb2-c8cf-11e4-8d8f-1ff419462ff0.JPG)
![androi](https://cloud.githubusercontent.com/assets/1327592/6618986/aa16ea76-c8cf-11e4-860e-838fcf509252.JPG)

**Comment by fidoboy** [comment]
It happens the same with navigation bar, it's not with tab bar only. See related issue here: https://github.com/AppGyver/steroids/issues/659 . Also, not directly related but also interesting here: https://github.com/AppGyver/steroids/issues/632#issuecomment-78100318
