### ISSUE TITLE
Application launch URL is not immediately available when app is coldstarted

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#868]
If you open a standalone iOS app that is closed via its custom URI scheme link (i.e. "coldstart" it), and immediately call `steroids.app.getLaunchURL()` (or `supersonic.app.getLaunchURL()`), it will not work. 

**WORKAROUND:** if you wrap it in the `steroids.on("ready")` event listener, it will return the URL correctly:

```
steroids.on("ready", function() {
  alert(steroids.app.getLaunchURL());
});
```

All Steroids function calls should implement the ready listener internally where needed, so this is a bug.

**Comment by harsaharsa** [comment]
A fix is now available. You need `4.0.5-edge10` client and the `next` branch of Steroids.js; which will allow you to use the new `steroids.app.getLaunchURI()` method:

```coffeescript
steroids.app.getLaunchURI {},
  onSuccess: (uri)->
    console.log "App was launched with URI #{uri}"
```

The `4.0.5-edge10` release also deprecates `steroids.app.getLaunchURL` (which was working erroneously in any case).

**Comment by sebmartel** [comment]
Fantastic news! Will there be an updated iOS edge for api parity?

**Comment by harsaharsa** [comment]
It's on the backlog!

**Comment by roberto-robles** [comment]
Maybe a n00b question but how can I test that Next branch on my project? I have pushed some builds using latest Android edge runtime environment, and I can't access getLaunchURI as part of steroids.app JS object.

**Comment by harsaharsa** [comment]
You need to locally copy the [steroids-js](http://ithub.com/appgyver/steroids-js) repo, checkout the `next` branch, run the Grunt build script and then copy the result from `dist/` into your app project.

**Comment by harsaharsa** [comment]
Available now with Steroids.js 3.5.11 and Android native runtime 4.0.5!
