### ISSUE TITLE
How to integrate TestFairy iOS SDK?

### ISSUE THREAD

**Issue by jubilem** [AppGyver/steroids#880]
Hello, and thanks for the awesome toolchain & UI framework!

I was able to build an iOS app and distribute it with TestFairy, but is it possible to integrate TestFairy iOS SDK (https://app.testfairy.com/sdk/ios/)? 

As far as I understood, I would need to compile the SDK with Xcode into the project, but looks like building steroids app with Xcode is not supported. Is there another ways to make it happen?

Thanks,
Juha

**Comment by jubilem** [comment]
Found the way, TestFairy was easily integrated via Cordova plugins, just added 

```javascript
[
  {"source":"https://github.com/testfairy/testfairy-cordova-plugin.git"}
]
```
into Plugin Configuration in build settings, and added required TestFairy.begin() into code.

Thanks,
Juha

**Comment by harsaharsa** [comment]
Great you figured it out. :) Closing this issue.
