### ISSUE TITLE
Inconsistent drawer/back swipe behaviour between iOS and Android

### ISSUE THREAD

**Issue by chrisnicola** [AppGyver/steroids#886]
On iOS when you have a view on the stack swiping from the left to right will take you back to the rootView, however on Android it opens the drawer instead.

While this probably isn't serious most of the time, it is inconsistent.

**Comment by harsaharsa** [comment]
It's the iOS native swipe-to-go-back gesture that doesn't exist on Android – you can disable the iOS feature by setting `webview.enablePopGestureRecognition: false` in `config/app.coffee`.

It's behavior-as-expected, so I'm closing this (should be better documented though if this was unclear).
