### ISSUE TITLE
Add a YouTube Video to AppGyvers app screen that looks like a YouTube Video was Dragged and Droped there than can be edited by a user to upload a video

### ISSUE THREAD

**Issue by TB99** [AppGyver/steroids#889]
Please help!

THanks

TB99

**Comment by harsaharsa** [comment]
This doesn't sound like an bug or a feature request, more of a HTML5 implementation of a specific feature, for which StackOverflow or the AppGyver forums are the correct place for discussion and help. Furthermore, I do not understand what you're trying to say. Please rephrase this in a more coherent manner.
