### ISSUE TITLE
<super-navbar-title> text not centred for Android when back button is present

### ISSUE THREAD

**Issue by budda** [AppGyver/steroids#903]
The title text in the nav bar doesn't appear to be getting centered in Android when a back button appears in the left side of the super-navbar.

I'm testing with Android Lollipop on a real HTC device for what it is worth.
The functionality appears fine in iOS.

Problem noticed in my own project, and seen in the Kitchensink app too.

**Comment by poppahorse** [comment]
+1, seems to happen on Jellybean also

**Comment by harsaharsa** [comment]
Duplicate of https://github.com/AppGyver/steroids/issues/843 – sorry for not having tackled this yet!
