### ISSUE TITLE
Rejected layer push – The specified child already has a parent

### ISSUE THREAD

**Issue by poppahorse** [AppGyver/steroids#913]
Trying to start or launch a view from a push notification, but getting the following error
```
supersonic.logger.error: supersonic.ui.layers.push rejected: {}
Possibly unhandled Error: The specified child already has a parent. You must call removeView() on the child's parent first.
    at FreshAndroidBridge.steroids.layers.push.onFailure (http://localhost/components/supersonic/supersonic.js:29000:29)
    at Object.send.callbacks.failure (http://localhost/components/steroids-js/steroids.js:101:40)
    at Object.callbacks.(anonymous function) (http://localhost/components/steroids-js/steroids.js:167:42)
    at FreshAndroidBridge.message_handler (http://localhost/components/steroids-js/steroids.js:201:45)
    at FreshAndroidBridge.message_handler (http://localhost/components/steroids-js/steroids.js:3321:59)
    at <anonymous>:1:23
```
here is what I am doing
```
supersonic.ui.views.find(pushpay.room).then( function(startedView) {
   if(startedView) {
      supersonic.ui.layers.push(startedView);
      //steroids.layers.push(startedView);
   }
   else {
      var view = new supersonic.ui.View({
         location: "messages#index",
         id: "room-x"
      });
			
      // Starting a view
      view.start().then(function(startedView2) {
         supersonic.ui.layers.push(startedView2);
      });
   }
});
```

I made a thread here - https://forums.appgyver.com/#!/steroids:rejected-layer-push-the-s and it seems you are unable to find and push a view that has already been pushed, which I am not trying to do, but does that also apply to views that have been started programatically and NOT pushed? 

Also would pushing a layer across different tab stacks make any difference? Hoping to accomplish the following:

Tab A, controller loads views so that a) certain layers are preloaded and b) so they don't close when you press back
Tab B, controller handles push notifications. When push notification is selected, should take the view id from the payload and `find` to see if the layer exists. If exists, push the layer, if not, create it.

**Comment by harsaharsa** [comment]
If you have a started view, then that view can only exist once in your application – either pushed to a layer stack or outside it. This applies across tabs, too – one started view cannot be in two tabs. (However, you can have the same HTML document in two started views.)

I can't 100% decipher your code from a quick glance, but if you look at e.g. the available WebViews in Chrome Inspector, you should be able to see that the view you're trying to push already exists in the layer stack.

**Comment by poppahorse** [comment]
Yes its definitely existing somewhere else in another stack so that does make sense. I started playing with some pub/sub stuff earlier to see if that would help, which by the sounds of it, it will. Thanks for getting back to me, much appreciated!

**Comment by harsaharsa** [comment]
Alright. Closing this issue!

**Comment by dantabel** [comment]
I understand that a webview can only be in the layer stack once, but is there a way to detect whether a view is already in the layer stack or not?

I have an app that contains posts, and individual posts can be opened from various places in the app. To speed things up I have a pre-loaded webview as a template and the post data gets swapped out when opened. So when I open a post I need to know whether the template is already in use or not so I know whether I can use the template or if I need to start a new view. 

Any help or pointers would be appreciated. Thanks.

**Comment by harsaharsa** [comment]
You could use the `steroids.getApplicationState()` method and iterate through the layer stacks looking for the view ID, similar to what Supersonic `View.isStarted` method does:

https://github.com/AppGyver/supersonic/blob/master/src/supersonic/core/ui/View.coffee#L117-L127

A PR for `View.isInLayerStack` would be welcome, too! :)

**Comment by dantabel** [comment]
Thanks for the tip. It seems though that when I call `getApplicationState()` it only contains 1 property `preloads`. According to the steroids docs it should contain `tabs` and `drawers` too. I need to access the tabs to get to the layer stack. 

I'd be happy to submit a PR if I can get this sorted.

**Comment by dantabel** [comment]
Shall I create a separate issue for the missing properties `tabs` and `drawers` in `steroids.getApplicationState()`? Or am I doing something wrong?

**Comment by harsaharsa** [comment]
I think that's actually a missing feature from the Android side; we only ever needed the `preloads` array on Android so the `tabs` and `drawers` was not implemented... Sorry. :( I even found the old issue at https://github.com/AppGyver/steroids/issues/850

You could always do a workaround where you try to push the preloaded layer, catch the error of "could not push view twice to layer stack" and then open a new view instead.

**Comment by dantabel** [comment]
Yeah, I tried that, the app completely freezes (requiring a force close) every time I try to push a view already in use. I can get an alert to pop up on fail, but I can't recover the app. 

Thanks for your help though.

**Comment by harsaharsa** [comment]
It should not freeze though, it should just give an error callback. If you can create a new issue, I'll add checking this to the backlog (repro app is a plus).

**Comment by dantabel** [comment]
New issue created for the freeze problem. [#1011](https://github.com/AppGyver/steroids/issues/1011)
