### ISSUE TITLE
Android Preview

### ISSUE THREAD

**Issue by mohamedsoufan** [AppGyver/steroids#916]
Hey, I started using AppGyver from an hour ago and I was wondering, why I can't preview my app on Android? Is AppGyver only for IOS or I also can create apps for Android?
I've downloaded the App Preview on my Android device and I scanned my barcode but it's not working.. It is loading all the time and it doesn't open my project to test it.

Thank you!

**Comment by harsaharsa** [comment]
I assume you are using Composer – that is currently for iOS only. The communications are a bit unclear, sorry for that!

**Comment by mohamedsoufan** [comment]
Yes I'm using Composer; What should I use to create Android apps and preview them from an Android device?

**Comment by mohamedsoufan** [comment]
The Logic System is not available for Android? I mean the drag-and-drop one..

**Comment by harsaharsa** [comment]
https://builder.apparchitect.com is the only visual tool currently out and available for Android (more is to come). Since this is not an actual issue, I'm closing the ticket.

**Comment by mohamedsoufan** [comment]
Why there is no Database feature in https://builder.apparchitect.com ?

By the way, I built an Application using the Composer and I've installed it on my Android device but there's a problem with the zoom in the page.. It is zoomed out!
Can I fix this problem? If so, I will use the composer to create my Android Apps it is much better than builder.apparchitect.com because it has a Database.

Thank you!

**Comment by harsaharsa** [comment]
AppArchitect is meant to be a simpler product, so there are no databases or other complexities.

Android is not supported with Composer so there might be other issues, but you can add a tag to the layout HTML file to make the scale correct:

```
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
```

**Comment by mohamedsoufan** [comment]
I haven't found the HTML file.. Can you please help me to find it?
I really appreciate your help.
Thank you! :)

**Comment by harsaharsa** [comment]
I think it'll be `app/views/layouts/application.html` or similar – you can search for e.g. the `<head>` tag in the exported project.

**Comment by mohamedsoufan** [comment]
Hello Harsaharsa,
I tried it but it didn't work.
Are you sure it can be fixed?
Please help me I'm very interested by your platform.

Thank you!
