### ISSUE TITLE
Facebook Plugin Does Not Retain Session on App Reopen

### ISSUE THREAD

**Issue by lyonsrob** [AppGyver/steroids#917]
I have verified this on the latest scanner using the addons-kitcken-sink (https://github.com/AppGyver/addons-kitchensink). 

Here is the repro steps: 

1.) Open app and navigate to Facebook App page
2.) Login with Facebook, verify login status is true
3.) Close app and reopen
4.) Navigate to Facebook App page, verify login status is true
5.) Close app and reopen
6.) Navigate to Facebook App page, verify login status is false. 

I've also noticed that dismissing a view after successfully logging a user in with Facebook also invalidates the session on app close/reopen. 

Is anybody experiencing the same issues?

**Comment by harsaharsa** [comment]
Discussion in the official FB plugn issue tracker: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/977

**Comment by harsaharsa** [comment]
This should be fixed after https://github.com/AppGyver/phonegap-facebook-plugin/pull/2 was merged. Please comment if issue is still there!
