### ISSUE TITLE
Build service does not sign App store builds, can't release new versions

### ISSUE THREAD

**Issue by tuomaslahti** [AppGyver/steroids#918]
Hi,

Application loader gives me this error message when I try to upload a new build to App store:

ERROR ITMS-90035: “Invalid Signature. Code object is not signed at all. The binary at path [myapp.app/Application/build/components/moment/scripts/npm_prepublish.sh] contains an invalid signature. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose ”Clean All“ in Xcode, delete the ”build“ directory in the Finder, and rebuild your release target. For more information, please consult developer.apple.com/…/Introduction.html”

I have released a lot of successful builds of this app before, but since yesterday (22.4.) Application loader refuses to upload the app to App store because the code is not signed.

My distribution certificate was not expired, but I tried creating a new certificate anyway. Still the Application loader gives me the same error.

Is something broken in the build service or is this caused by something else?

**Comment by amv** [comment]
Just a quick update: We managed to upload a new build now. A likely reason for this was downgrading moment.js in our project from 2.8.4 to 2.8.3.

We lack deeper understanding on why this affected submitting a build. But if you are struggling with the same problem, this might help.

**Comment by tuomaslahti** [comment]
I looked through a couple of earlier app packages that have been successfully uploaded to App store. Looks like we have been using moment.js 2.8.4 in our previous releases as well, but for some reason now it's causing this problem.

**Comment by harsaharsa** [comment]
Sounds pretty weird, but great to hear you figured it out. Do tell us if you can reproduce this – I'll keep the ticket open to monitor if the issue appears again. Perhaps excluding the whole bower components directory from the build will help, i.e. just include the JS files?

**Comment by hexorx** [comment]
I'm having the same issue using Moment 2.10.2

![skitch](https://cloud.githubusercontent.com/assets/2915/7422141/97ceb454-ef47-11e4-852c-07d4268a6ed2.png)

**Comment by eladelrom** [comment]
I was having the same issue with the latest version of moment, I solved this by just using "moment.min.js" and removing the entire bower component folder. I uglify and adding all the files for deployment so this is another option for ppl with issues around xcode deployment.

**Comment by kelvinhokk** [comment]
I ended up writing a cordova hook to remove all the bower component folders in the moment folder.

**Comment by kayzee** [comment]
I cannot believe this was the solution! I spent 1.5 hours on Friday trying to figure out what was wrong with the App Store submit process and this solved it perfectly.

> I was having the same issue with the latest version of moment, I solved this by just using "moment.min.js" and removing the entire bower component folder. I uglify and adding all the files for deployment so this is another option for ppl with issues around xcode deployment.

**Comment by harsaharsa** [comment]
I created a new issue about this to https://github.com/AppGyver/steroids/issues/929 that has a more clear definition of the problem, so I'm closing this issue.
