### ISSUE TITLE
External Script are not loaded in sequence.

### ISSUE THREAD

**Issue by JugnuPathak** [AppGyver/steroids#920]
By putting script in common/javascripts its included in common.js in random order but i want scripts to be loaded in sequence because my second script file is depended one first one. How can i load them in sequence?

**Comment by Gniller** [comment]
Take a look at: https://api.jquery.com/jquery.getscript/ . It offers success callbacks on loading scripts, which allows you to sequence the loading process.

**Comment by JugnuPathak** [comment]
But script file code are automatically get appended in common.js and its causing problem.

**Comment by JugnuPathak** [comment]
@harsaharsa any idea?

**Comment by Gniller** [comment]
I use my script files from the components directory, where they won't get appended and are directly accessible over http://localhost/components/. This goes only for script files that require to remain accessible independently and not for regular view scripts.

**Comment by JugnuPathak** [comment]
components folder is created on run time. How to place my script files in it?

**Comment by Gniller** [comment]
The components folder is generated from the /bower_components/ folder in your steroids project. Any files added in here are included in the generation of the components folder.

**Comment by JugnuPathak** [comment]
Its working thanks.
