### ISSUE TITLE
should i use  supersonic.bind($scope, function)?

### ISSUE THREAD

**Issue by JugnuPathak** [AppGyver/steroids#922]
I have a requirement in which i want javascript function to continuously run in background regardless or view .how can i achieve that?
deviceready is fired on each view. But i want to call function ones in initial view and  keep it running in background. 
should i use supersonic.bind($scope, function) to acehive my goal?

**Comment by justincolangelo** [comment]
You can use `supersonic.bind()` for this. You can also use [$rootScope](https://docs.angularjs.org/api/ng/service/$rootScope), though most developers I have talked with on this issue are using Superscope.

**Comment by JugnuPathak** [comment]
Function will check for network and if network is available it will send all data from indexeddb to server. Function will continue to run on specific time interval. 
So what will be perfect one supersonic.bind() or superscope? @justincolangelo

**Comment by justincolangelo** [comment]
Here is an example of a service that has a `setInterval()` call in the $rootScope. [Self Updating Data Service](http://stackoverflow.com/questions/18356840/self-updating-service-injected-to-the-controller)
I haven't tested something like this on an Appgyver application, yet. I use $rootScope for a few things in my Appgyver application, but not for this at the moment.

**Comment by JugnuPathak** [comment]
will this work on multipage appgyver application ? Because for each view new instance of webview with all script reference is created. So on each view angular service or controller will be reinitialized.

**Comment by justincolangelo** [comment]
Is it all part of one module? I am relying on SO posts because this type of question has been answered many times on there. Here is one example that can share a service across modules/apps: [Share Service](http://stackoverflow.com/questions/16725392/share-a-single-service-between-multiple-angular-js-apps)
