### ISSUE TITLE
tabs.whenDidChange()

### ISSUE THREAD

**Issue by laicosly** [AppGyver/steroids#937]
Uncaught TypeError: supersonic.ui.tabs.whenDidChange(...).then is not a function

```javascript
supersonic.ui
	.tabs
	.whenDidChange()
	.then(function () {
		supersonic.logger.log("Tabs will change", arguments)
	})
```

**Comment by laicosly** [comment]
The docs demonstrate whenDidChange & whenWillChange returning a promise, but supersonic.js expects a callback, and returns an unsubscribe method.

http://docs.appgyver.com/supersonic/api-reference/stable/supersonic/ui/tabs/whendidchange/

```javascript
whenDidChange: function(f) {
      var id;
      id = steroids.tabBar.on("didchange", f);
      return function() {
        return steroids.tabBar.off("didchange", id);
      };
    }
```

**Comment by harsaharsa** [comment]
Thanks for catching this. I've updated the docs now!
