### ISSUE TITLE
Upgrade to Cordova 5.0

### ISSUE THREAD

**Issue by laicosly** [AppGyver/steroids#938]
https://cordova.apache.org/

this 3.5 cordova issue is affecting our app w/ the actionsheet plugin.   https://issues.apache.org/jira/browse/CB-6761

**Comment by kaiserlos** [comment]
+1

**Comment by harsaharsa** [comment]
Cordova iOS is actually at 3.8.0 and Cordova Android at 4.0.0:

https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md#release-400-march-2015
https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#380-201502xx

It's just the tooling (that we don't use directly) that's on version 5.0. So, closing this and keeping https://github.com/AppGyver/steroids/issues/732#issuecomment-102398411 open instead.
