### ISSUE TITLE
iOS support for SPDY protocol communication

### ISSUE THREAD

**Issue by kaiserlos** [AppGyver/steroids#939]
I changed my server to use the SPDY protocol for faster secure communication and the app couldn't make ajax requests anymore at all. Loading my SPDY page in safari browser works.

**Comment by harsaharsa** [comment]
The `UIWebView` is probably lacking behind in features support compared to Mobile Safari. Not sure when this will come up in the backlog (you're the first one to request this), plus we'd need to add it to Android also for feature parity. I'd suggest adding an additional HTTP endpoint in the meantime for the mobile app.

**Comment by neophob** [comment]
btw SPDY is dead, see http://en.wikipedia.org/wiki/SPDY:

Throughout the process, the core developers of SPDY have been involved in the development of HTTP/2, including both Mike Belshe and Roberto Peon. As of February 2015, Google has announced that following the recent final ratification of the HTTP/2 standard, support for SPDY would be deprecated, and that support for SPDY will be withdrawn completely in 2016.[6]

**Comment by harsaharsa** [comment]
Aight, closing this as definite #wontfix then :)
