### ISSUE TITLE
Data model not taking into account query parameters

### ISSUE THREAD

**Issue by amitrack** [AppGyver/steroids#940]
Hello there ,
I'm trying to use Supersonic to communicate with a custom backend and I'm trying to use query parameters on both all() and findAll() to no avail, 
with either all({date:timestamp}) and findAll({date:timestamp}) instead of getting 
/my/url/here?date:timestamp , I'm getting /my/url/here .
I really I'm thankful for the tremendous work you're putting into this amazing project and I would be even more if you could look into it .
Amine

**Comment by harsaharsa** [comment]
So when you say "getting", you mean "your backend is receiving", right? It could be that you need to whitelist the allowed query parameters by clicking the "Customize Actions" button under the Resource in the data manager and adding them under "Query Parameters". Does that have an effect?

**Comment by amitrack** [comment]
Thanks , It's fixed , it was a mistake on my side
