### ISSUE TITLE
how to inject ngAnimate??

### ISSUE THREAD

**Issue by mydearxym** [AppGyver/steroids#941]
amazing work!

i just don't know how to inject any third-part modules in AppGyer app 
i tried in index.js: 
```javascript 
angular.module('common', [
  // Declare here all AngularJS dependencies that are shared by all modules.
  'supersonic',
  'ngAnimate'
]);

```

tried in 
```javascript
angular
  // .module('example', ['angular-velocity'])
  .module('example', ['ngAnimate'])

```
none of those works , it drives me crazy ....

**Comment by justincolangelo** [comment]
Did you run `bower install ngAnimate` and verify that you have the script included in your `layout` file? Check out the `/dist` folder and make sure the script exists.

    <script src="/components/angular/angular.js"></script>
    <script src="/components/ngAnimate/js/angular-animate.min.js"></script>

And in the controller:

    angular
        .module('example', ['ngAnimate'])
        .controller('LearnMoreController', function($scope, supersonic) {
            // do things here
        });

You could also try this instead as you had it:

    angular.module('common', [
        // Declare here all AngularJS dependencies that are shared by all modules.
        'supersonic',
        'ngAnimate'
    ]);

And then in your controller:

    angular
        .module('example', [])
        .controller('LearnMoreController', function($scope, supersonic) {
            // do things here
        });

Notice the `.module('example', []) with empty array.

**Comment by harsaharsa** [comment]
I'm closing this since this is an AngularJS-specific question and doesn't have to do with issues/features of Steroids/Supersonic per se. Please continue the discussion on https://forums.appgyver.com, if @justincolangelo's excellent answer didn't solve it already. :)

**Comment by mydearxym** [comment]
@justincolangelo  @harsaharsa 
I tried those answer ,  none of those works 
[here](https://github.com/mydearxym/mydearym/blob/master/app/common/views/layout.html) and [here](https://github.com/mydearxym/mydearym/blob/master/app/example/scripts/DashboardController.js) is the source code 

in my case i can't add any 3-part injection ...
