### ISSUE TITLE
Injector Module Error with Default SPA CRUD Scaffolding

### ISSUE THREAD

**Issue by merktassel** [AppGyver/steroids#944]
After creating a single page application and adding a Parse resource, the default CRUD scaffolding generated doesn't render any data and returns an error in the logs: 

> "Error: [$injector:modulerr] Failed to instantiate module place due to:\n[$injector:modulerr] Failed to instantiate module common due to:\n[$injector:nomod] Module 'common' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.\nhttp://errors.angularjs.org/1.3.15/$injector/nomod?p0=common\nhttp://localhost/components/angular/angular.js:63:32\nhttp://localhost/components/angular/angular.js:1774:32\nensure@http://localhost/components/angular/angular.js:1698:45\nmodule@http://localhost/components/angular/angular.js:1772:20\nhttp://localhost/components/angular/angular.js:4115:35\nforEach@http://localhost/components/angular/angular.js:323:24\nloadModules@http://localhost/components/angular/angular.js:4099:12\nhttp://localhost/components/angular/angular.js:4116:51\nforEach@http://localhost/components/angular/angular.js:323:24\nloadModules@http://localhost/components/angular/angular.js:4099:12\ncreateInjector@http://localhost/components/angular/angular.js:4025:22\ndoBootstrap@http://localhost/components/angular/angular.js:1452:34\nbootstrap@http://localhost/components/angular/angular.js:1473:23\nangularInit@http://localhost/components/angular/angular.js:1367:14\nhttp://localhost/components/angular/angular.js:26304:16\ntrigger@http://localhost/components/angular/angular.js:2762:9\neventHandler@http://localhost/components/angular/angular.js:3032:25\nhttp://errors.angularjs.org/1.3.15/$injector/modulerr?p0=common&p1=%5B%24injector%3Anomod%5D%20Module%20'common'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.15%2F%24injector%2Fnomod%3Fp0%3Dcommon%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A63%3A32%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1774%3A32%0Aensure%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1698%3A45%0Amodule%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1772%3A20%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4115%3A35%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4116%3A51%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4025%3A22%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1452%3A34%0Abootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1473%3A23%0AangularInit%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1367%3A14%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A26304%3A16%0Atrigger%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A2762%3A9%0AeventHandler%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A3032%3A25\nhttp://localhost/components/angular/angular.js:63:32\nhttp://localhost/components/angular/angular.js:4138:30\nforEach@http://localhost/components/angular/angular.js:323:24\nloadModules@http://localhost/components/angular/angular.js:4099:12\nhttp://localhost/components/angular/angular.js:4116:51\nforEach@http://localhost/components/angular/angular.js:323:24\nloadModules@http://localhost/components/angular/angular.js:4099:12\ncreateInjector@http://localhost/components/angular/angular.js:4025:22\ndoBootstrap@http://localhost/components/angular/angular.js:1452:34\nbootstrap@http://localhost/components/angular/angular.js:1473:23\nangularInit@http://localhost/components/angular/angular.js:1367:14\nhttp://localhost/components/angular/angular.js:26304:16\ntrigger@http://localhost/components/angular/angular.js:2762:9\neventHandler@http://localhost/components/angular/angular.js:3032:25\nhttp://errors.angularjs.org/1.3.15/$injector/modulerr?p0=place&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20common%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'common'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.15%2F%24injector%2Fnomod%3Fp0%3Dcommon%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A63%3A32%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1774%3A32%0Aensure%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1698%3A45%0Amodule%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1772%3A20%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4115%3A35%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4116%3A51%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4025%3A22%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1452%3A34%0Abootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1473%3A23%0AangularInit%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1367%3A14%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A26304%3A16%0Atrigger%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A2762%3A9%0AeventHandler%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A3032%3A25%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.15%2F%24injector%2Fmodulerr%3Fp0%3Dcommon%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'common'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.3.15%252F%2524injector%252Fnomod%253Fp0%253Dcommon%250Ahttp%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A63%253A32%250Ahttp%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1774%253A32%250Aensure%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1698%253A45%250Amodule%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1772%253A20%250Ahttp%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A4115%253A35%250AforEach%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A323%253A24%250AloadModules%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A4099%253A12%250Ahttp%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A4116%253A51%250AforEach%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A323%253A24%250AloadModules%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A4099%253A12%250AcreateInjector%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A4025%253A22%250AdoBootstrap%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1452%253A34%250Abootstrap%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1473%253A23%250AangularInit%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A1367%253A14%250Ahttp%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A26304%253A16%250Atrigger%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A2762%253A9%250AeventHandler%2540http%253A%252F%252Flocalhost%252Fcomponents%252Fangular%252Fangular.js%253A3032%253A25%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A63%3A32%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4138%3A30%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4116%3A51%0AforEach%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A323%3A24%0AloadModules%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4099%3A12%0AcreateInjector%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A4025%3A22%0AdoBootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1452%3A34%0Abootstrap%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1473%3A23%0AangularInit%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A1367%3A14%0Ahttp%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A26304%3A16%0Atrigger%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A2762%3A9%0AeventHandler%40http%3A%2F%2Flocalhost%2Fcomponents%2Fangular%2Fangular.js%3A3032%3A25 - undefined:undefined"

It also seems to freeze the scanner if you try to add a new item. I created a single page application from scratch and didn't add anything other than the default CRUD scaffolding to try to isolate the issue, and it occurred again. A second repeat on a different machine confirmed this. As far as I can tell, it doesn't occur with multi page applications, but does occur with any of the resource providers (Parse and AppGyver Sandbox tested). 

**Desktop OS:** Yosemite 10.10.3 (14D136)
**Steroids CLI:** 4.0.15
**Steroids.js:** 3.5.10
**Scanner:** 4.0.31
**Device:** iPhone 6 Plus
**Mobile OS:** iOS 8.3 (12F70) 
**Platforms Affected:** Only Tested iOS
**Problem Occurs in:** Scanner and Simulator

**Comment by harsaharsa** [comment]
Ah, that's true – the CRUD scaffolding expects the `common` module to be there, and that's only generated with the MPA structure. Until this is addressed properly, a fix is to copy the `app/common/` folder from a new MPA project over to your SPA project.

**Comment by merktassel** [comment]
The quick fix you provided only seemed to fix part of the problem. The default scaffolding now works for the index page (listing all entries), but trying to select a specific entry to load the show page gets stuck at waiting.

**Comment by merktassel** [comment]
Using the default settings (MPA and Coffeescript), I created a new application from scratch and generated a scaffold using a basic set of data on the AppGyver Sandbox Database. The same issue occurred: I'm able to list all of the data on the index page, but selecting a specific entry gets stuck at waiting instead of rendering the show page. Creating a new entry also doesn't work; it just hangs at the spinner and says waiting.

**Comment by harsaharsa** [comment]
We had a brief bug in the data backend that caused some requests to fail, and it sounds like you were hit with that. If you try again now that we've fixed the issue, does it still persist?

**Comment by merktassel** [comment]
The issue seems to be fixed now. Do you have a status page that I can check for outages like that? I was racking my brain trying to figure out what the problem was, and even went so far as to reinstall and restart everything to make sure it wasn't just me.

**Comment by harsaharsa** [comment]
Yup, you can find this incident at http://status.appgyver.com/incidents/4v6lxpp0d1vg

I'm closing this ticket now that everything seems to be in order. Sorry for your trouble!
