### ISSUE TITLE
Cannot push or replace layers from inside a drawer

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#946]
Android-only. See https://github.com/AppGyver/steroids/issues/376 for related iOS issue.

**Comment by harsaharsa** [comment]
Fix available in 4.0.6-edge1!

**Comment by fidoboy** [comment]
Not sure if it's related but unload method fails with latest edge for Android. Returned error from the unload function is:

```A preloaded layer with identifier http://localhost/.....html could not be found```

the replace method does not allow to unload the old webView.

**Comment by harsaharsa** [comment]
If you use `steroids.getApplicationState`, does it show that there's a preloaded view with the exact ID you're trying to unload? Does the same code work with 4.0.5?

**Comment by fidoboy** [comment]
No, the unload method never worked on Android from drawer. getApplicationState does not return the list of all loaded layers only some of them
