### ISSUE TITLE
Authentication/Session cookies wiped after app restart

### ISSUE THREAD

**Issue by aminecmi** [AppGyver/steroids#951]
When receiving a "Set-Cookie" header from an API, the cookie is set correctly, but it is wiped/deleted when I close the app.
**I only experienced this on IOS, as I'm only testing on IOS now.**

**Steps:**
- Call an API that have a "Set-cookie" header.
- Make another call that requires that cookie set to check if it is set.
- Close the app. (On IOS double tap the home button, and then swipe up the app)
- Try to call the call that required the cookie set. It will fail.

**Strange case:**
The strange thing is that when the steroids CLI reloads the app after some changes, the cookies are still working.

**Comment by harsaharsa** [comment]
Can you create a repro project (with an appropriate API) where this fails?
