### ISSUE TITLE
Can't launch simulator after update with no error.

### ISSUE THREAD

**Issue by aminecmi** [AppGyver/steroids#952]
I just updated steroids (The “steroids” commands show v4.1.5) and I can't launch the IOS simulator.

After starting “steroids connect”, and typing “s” or “sim” and enter key, nothing happen.
If the simulator is open, it will close and don't start.

I tried to create a new empty app, but the result is the same. The simulator won't start, and I have no error message.

**Comment by harsaharsa** [comment]
If you downgrade to v4.1.4, does it work fine? The update did contain fixes to the iOS Simulator (to fix the 200% CPU issue), so it might have affected something. What OS X version are you using? Can you open the iOS Simulator via the Connect Screen menu?

**Comment by aminecmi** [comment]
I'm running osX 10.9.5

With the debug option, here is the errors I get:
```
s
AppGyver Steroids command  
Starting iPhone-6 Simulator
[DEBUG] Fri May 29 2015 17:06:06 GMT+0200 (CEST) Killed iOS Simulator.
[DEBUG] Fri May 29 2015 17:06:06 GMT+0200 (CEST) Spawning /Users/ME/lib/node_modules/steroids/node_modules/ios-sim/bin/ios-sim
[DEBUG] Fri May 29 2015 17:06:06 GMT+0200 (CEST) with params: launch,/Users/ME/lib/node_modules/steroids/node_modules/steroids-ios-packages/simulators/Simulator-4.0.3.app,--devicetypeid,com.apple.CoreSimulator.SimDeviceType.iPhone-6,--verbose
2015-05-29 17:06:06.260 ios-sim[10284:507] -[__NSCFString containsString:]: unrecognized selector sent to instance 0x7fc5b1e00b10

2015-05-29 17:06:06.261 ios-sim[10284:507] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsString:]: unrecognized selector sent to instance 0x7fc5b1e00b10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff91a0525c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8adcbe75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff91a0812d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff91963272 ___forwarding___ + 1010
	4   CoreFoundation                      0x00007fff91962df8 _CF_forwarding_prep_0 + 120
	5   ios-sim                             0x000000010afe7571 -[iPhoneSimulator runWithArgc:argv:] + 1245
	6   ios-sim                             0x000000010afe7e7c main + 101
	7   ios-sim                             0x000000010afe5140 start + 52
	8   ???                                 0x0000000000000006 0x0 + 6
)

libc++abi.dylib: terminating with uncaught exception of type NSException

[DEBUG] Fri May 29 2015 17:06:06 GMT+0200 (CEST) Killing iOS Simulator ...
[DEBUG] Fri May 29 2015 17:06:06 GMT+0200 (CEST) Killed iOS Simulator.
```

**Comment by aminecmi** [comment]
Is there some news regarding this bug ?

**Comment by harsaharsa** [comment]
We can't get this to reproduce on our end, unfortunately. What Xcode and OS X version are you using? Could you try reinstalling Xcode?

**Comment by aminecmi** [comment]
I'm using the same Xcode I was using before. It wasn't updated. It's XCode Version 6.0.1 (6A317)

**Comment by aminecmi** [comment]
After trying to launch the simulator from the connect screen, I have this message:
```
Connection lost!

Cannot connect to the Steroids Development Server! Start the Steroids Development Server by running steroids connect in Terminal in your project directory.
```

The ```steroids connect``` command is running, and the log show no error. 
Maybe this is the problem ?

**Comment by aminecmi** [comment]
Any news on the issue ?

**Comment by jordangraft** [comment]
@aminecmi I was getting the same error after I updated Steroids.  I had to update my OS X to Yosemite and then updated my xcode version to 6.3.2 and it's working for me now.

**Comment by andybbtt11** [comment]
Yep, finally got our machines updated here at work and my issues are resolved as well. Thanks.
