### ISSUE TITLE
On Android 4.0.6-edge2, tab bars are less responsive to taps

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#956]
Compared to earlier Android versions, tapping on a tab bar image does not always change the tab. Tapping on the tab bar item title consistently work. This is likely due to fixes that enabled Android tab bar item to respond to the `background-size` CSS property properly.

**Comment by lemondesigns** [comment]
Correction to the above... tapping on the icon does not work - period. Tapping the text works.
Changing background-size or omitting it has no effect on result. It appears a change in 4.0.6-edge2 has removed the click event entirely from the icon (on Android only).

**Comment by fidoboy** [comment]
It happens something like this on navigation bar icons also, randomly they doesn't work. Tapping multiple times over them and it does nothing. This happens since the first steroids releases but lately it's more noticeable

**Comment by lemondesigns** [comment]
This is not a random occurrence however. It is constant. You can only change tabs by clicking the "text" in the tab as clicking any icon renders nothing. It is quite irritating since the text is quite small already and this makes it very confusing to the end-user. It is a vital fix.

**Comment by fidoboy** [comment]
You are right, but for nav bar it's random. The tappable area should be the whole surface, not only the painted zones

**Comment by dantabel** [comment]
+1 
I have to exact same experience, icons are not tappable but the text is. Using Android 4.4.4.

This is critical for me as I am not using text labels at all in my tab bar (font-size: 0), I'm using icons only. I was having problems with getFromPhotoLibrary that 4.0.6edge2 fixes, but this is also a show stopper for me.

**Comment by lemondesigns** [comment]
Yup... and resizing of the icon is not possible without the image distorting badly too.

Example:

tab-bar-item#settings {
  background-image: url(icons/cog.svg);
  background-size: 16;
}

This will render a badly blurred/pixilated version of the cog.svg

On my Android the default image size is tiny, on my iPhone the size is perfect. So I really need to be able to resize the icon / image - but not if it's going to look terrible!

**Comment by harsaharsa** [comment]
This is now fixed in 4.0.6-edge3! @fidoboy – have you found any consistent repro for the nav bar taps not responding? If so, please make a new issue out of it.

**Comment by dantabel** [comment]
Thank you! 
I can confirm that this is fixed for me in edge3, the tabs are now working as expected.

**Comment by fidoboy** [comment]
I'll test it with this new release to see if it solves also the problem with navbar. I don't see any way to reproduce it; it just happens with the tap event inside the angular controller. The event is not being triggered and the code does not executes. It does not happens always but it happens very often. Same code works always fine on iOS

**Comment by lemondesigns** [comment]
Thanks, I also confirm it's working on 4.0.6-edge3
