### ISSUE TITLE
Showing the nav bar does not trigger window.resize making it impossible to get window.innerHeight reliably on page load 

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#957]
Using the document ready event or DOM ready, window.innerHeight returns wrong value. Can't see any other way to get the current window height so steroids should provide any way to solve this issue.

**Comment by satusuuronen** [comment]
How is the value wrong (too small/too large)? Does the keyboard, navbar or tab bar visibility have any effect?

**Comment by fidoboy** [comment]
It doesn't take the navigation bar height into account and it returns the same than screen.height this works fine on iOS

**Comment by fidoboy** [comment]
If I try to debug this using the Chrome inspector, and I add a breakpoint on that line on DOM ready or document ready; then it works fine and returns the right value

**Comment by satusuuronen** [comment]
It seems like nav bar is not yet shown when the DOM ready fires and that's why window.innerHeight returns wrong value. We are working to fix these issues with nav bar. In the mean time, you could try to call window.innerHeight inside deviceready for a workaround.

**Comment by fidoboy** [comment]
I've already tried that workaround using deviceready event but it doesn't work fine. Sometimes it also fails and it's random

**Comment by fidoboy** [comment]
I believe that the right approach to achieve this is by adding a window resize trigger event to the nav bar. This way, when the navbar is being displayed or closed, the resize event is activated.

**Comment by satusuuronen** [comment]
That's a good suggestion. We'll see if we can set a window.resize event trigger.

**Comment by pentateu** [comment]
I could not reproduce this issue. I have tested on XWalk and Platform web view. Android 4.4 and 4.3

I have implemented the following test for innerHeight and innerWidth in our steroids-js/testApp to confirm 
that the innerHeight, innerWidth and the window.onresize event works fine on Android and iOS. 

```
document.addEventListener "deviceready", ->

    onresizeCounter = 0

    displayInnerSizes = ->
      document.getElementById("innerHeight").innerHTML  = window.innerHeight
      document.getElementById("innerWidth").innerHTML   = window.innerWidth
      document.getElementById("heightBar").style.height = "#{window.innerHeight}px"

    increaseOnResizeCounter = ->
      onresizeCounter++
      document.getElementById("onresizeCounter").innerHTML = onresizeCounter

    window.onresize = ->
      displayInnerSizes()
      increaseOnResizeCounter()

    displayInnerSizes()

  @testShowNavBar: ->
    steroids.view.navigationBar.show()

  @testHideNavBar: ->
    steroids.view.navigationBar.hide()

  @testShowTabBar: ->
    steroids.tabBar.show()

  @testHideTabBar: ->
    steroids.tabBar.hide()
```
