### ISSUE TITLE
Custom Backend Provider not requesting to localhost

### ISSUE THREAD

**Issue by Narzerus** [AppGyver/steroids#967]
I'm using a Custom Backend on localhost:3000, the problem is that the provider's requests do not reach the API if it is started on localhost.

I uploaded the same repository to a remote server and it works perfectly.

Am I doing something wrong here or is this a bug?

**Comment by harsaharsa** [comment]
Supersonic Data requests and responses go through our proxy, so you'd need to give the public-facing IP of your local server for the proxy to be able to tackle this. The proxy has no way of knowing what your public-facing IP is from just "localhost", so we can't do that automatically. Closing this as known issue.

**Comment by Narzerus** [comment]
Thanks, I'd suggest being more explicit on the docs with this one.

Also, may i ask why is the proxy connection necessary? This doesn't allow for a true development environment as you still need a connection to the web to test the app. Also, what if your proxy goes down? I'm not sure if this is actually a good idea.

Thanks for this great framework, I'd love to use this in production in the future!

**Comment by anotherstarburst** [comment]
I second this. I have a local version of a custom API on my development machine that I'd like to test my app against. Setting the query URL to http://localhost:3001 isn't working either :/
