### ISSUE TITLE
Update cordova version

### ISSUE THREAD

**Issue by RWOverdijk** [AppGyver/steroids#970]
Hello,

I'm trying to use a custom plugin (https://github.com/Telerik-Verified-Plugins/LocalNotification) which [requires at least cordova 3.6.0](https://github.com/Telerik-Verified-Plugins/LocalNotification/blob/master/plugin.xml#L22). Current builds seem to come with 3.5.0. Is there any way to update cordova for my project? I tried simply lowering the dependency in a fork, but then the builds fail.

Thank you.

**Comment by satusuuronen** [comment]
Unfortunately, there is no way to upgrade Cordova for you project on your own. Steroids support for Cordova 4.0 is coming at some point, please see [#732](https://github.com/AppGyver/steroids/issues/732#issuecomment-102398411). 

I am closing this issue and keeping the other issue open.
