### ISSUE TITLE
Unable to display images captured from supersonic.media.camera.takePicture()

### ISSUE THREAD

**Issue by sunny061** [AppGyver/steroids#972]
I choose the destinationType as the fileURI in the options.

And when I get the URL below, I am unable to add it as a src to the image. 

The error I am getting is:
Not allowed to load local resource: file:///storage/emulated/0/Android/data/com.testApp.www/cache/1434957344208.jpg

I am using a custom scanner because I am using a custom plugin. Also, the device I am running the app on is a Android 4.4.4. Also, what directory do I specify if I want to move it to "file:///data/data/com.testApp.www/files1434957344208.jpg" so that I can access it from "http://localhost/".

This is the function I plan to use to move the file:
var d = new Date();
var n = d.getTime();

//new file name
var newFileName = n + ".jpg";
var myFolderApp = "files";

window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function(fileSys) {      
        //The folder is created if doesn't exist
        fileSys.root.getDirectory( myFolderApp,
                        {create:false, exclusive: false},
                        function(directory) {
                          console.log('dire', directory)
                            entry.moveTo(directory, newFileName,  successMove, resOnError);
                        },
                        resOnError);
                        },
        resOnError);

**Comment by JugnuPathak** [comment]
steroids.app.absoluteUserFilesPath will gives you path - "/storage/sdcardName(e.g sdcard0)/Android/data/appidentifier(e.g com.testApp.test.scanner/files/user" where you can create your folder and put your camera image there to access it as img tag src.

**Comment by sunny061** [comment]
@JugnuPathak Thanks for the reply. I will try it out and get back to you if it works or not.

**Comment by sunny061** [comment]
@JugnuPathak Hi. Sorry for the late reply. But I can't seem to get it working. Is there a guide/tutorial on this topic? I want to take a file from my gallery/camera and move it to a folder inside the localhost so I can use it as a src in "img" tag.

**Comment by Leeds-eBooks** [comment]
@sunny061 did you fix this? It would be useful to know how, if so.

**Comment by JugnuPathak** [comment]
@sunny061  @Leeds-eBooks Sorry my previous answer was for moving your current captured from cache folder in @sunny061 case from file:///storage/emulated/0/Android/data/com.testApp.www/cache/1434957344208.jpg to file:///storage/emulated/0/Android/data/com.testApp.www/user/yourfoldername/1434957344208.jpg so it will be accessible from "http://localhost" because by default its stored in cache folder.

But if you want to move existing file from a folder in sdcard to  file:///storage/emulated/0/Android/data/com.testApp.www/user/yourfoldername/1434957344208.jpg then just use following code:

window.resolveLocalFileSystemURI("sourceFolderPath", function(file) {
   window.resolveLocalFileSystemURI("destinationFolderPath", function(destination) {
             file.moveTo(destination,filename);
   },function(){//fail callback})
},function(){//fail callback});

**Comment by sunny061** [comment]
@Leeds-eBooks I was able to take the image from the cache and move it to my folder using the following code and then I was able display it in my <img> tag:

    $scope.getFromGallery = function() { // You could use the 
      var options = {
        quality: 95,
        allowEdit: true,
        targetWidth: 300,
        targetHeight: 300,
        encodingType: "png",
      };
      supersonic.media.camera.getFromPhotoLibrary(options).then(function(result) {
        console.log('Image uri', result)
        movePic(result);
      });
    }

    function movePic(file){ 
        window.resolveLocalFileSystemURL(file, resolveOnSuccess, resOnError); 
    }

    function resolveOnSuccess(entry) {
      var d = new Date();
      var n = d.getTime();
      //new file name
      var newFileName = n + ".jpg";
      var myFolderApp = steroids.app.absoluteUserFilesPath + "/images";
      window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function(fileSys) {      
      //The folder is created if doesn't exist
      fileSys.root.getDirectory( myFolderApp,
                      {create:true, exclusive: false},
                      function(directory) {
                          entry.moveTo(directory, newFileName,  successMove, resOnError);
                      },
                      resOnError);
                      },
      resOnError);
     }

    function successMove(entry) {
      console.log('entry', entry) // entry.name will returns the filename with extension i.e. 21313.jpg
    }

    function resOnError(error) {
      console.log('error', error);
    }

And then I could display the image using...

<img src="/images/(entry.name)" />

**Comment by JugnuPathak** [comment]
Exactly that's the solution i gave your before why it wasn't working before @sunny061 ???

**Comment by sunny061** [comment]
@JugnuPathak I probably missed something at the time but it did worked eventually. Thanks for your help though.
