### ISSUE TITLE
After update iOS simulator crashes and does not load app properly

### ISSUE THREAD

**Issue by CodeBend** [AppGyver/steroids#978]
After the update, I can type s in the terminal and a simulator opens but it does not launch the app, I have to scroll and open to the app manually. After the app opens, it works for a few minutes then crashes. 
--edit sorry i am a noob... used sudo to update steroids.

**Comment by satusuuronen** [comment]
So @CodeBend you solved it?

**Comment by CodeBend** [comment]
yup, I got it working again by reinstalling node and steroids without sudo

**Comment by satusuuronen** [comment]
Glad to hear you got it solved! 

Closing this issue.
