### ISSUE TITLE
Link to these issues are broken in docs.appgyver.com

### ISSUE THREAD

**Issue by ViliusKraujutis** [AppGyver/steroids#984]
[Technical concepts](http://docs.appgyver.com/supersonic/guides/technical-concepts/) docs has a broken link. Instead of:
https://github.com/appgyer/steroids/issues should be:
https://github.com/appgyver/steroids/issues (note "v" is missing)

It's in this place:
>Reporting issues
All AppGyver-related issues are tracked centrally on GitHub. Before submitting a new issue, search through the issues to see if it has been opened or resolved already.

**Comment by satusuuronen** [comment]
Fixed.

**Comment by ViliusKraujutis** [comment]
:+1: thanks, @satusuuronen
