### ISSUE TITLE
Unable to include custom plugin cordova-plugin-zip

### ISSUE THREAD

**Issue by blanedaze** [AppGyver/steroids#986]
I had tried to use cordova-plugin-zip in my app, but it is not usable due to its dependency towards cordova-plugin-file, explained from this answer in [StackOverflow](https://stackoverflow.com/questions/30302647/error-404-cordova-plugin-file-when-trying-to-install-cordova-plugin-zip-for-ios/30344258#30344258). 

The error it produced from build failed log:
`Adding plugin from: https://github.com/MobileChromeApps/cordova-plugin-zip.git
Failed to fetch package information for cordova-plugin-file`

I had tried to fix this based on the answer by attempting to include https://github.com/apache/cordova-plugin-file.git into the plugin list, but it returns this error from the build failed log:

`Adding plugin from: https://github.com/apache/cordova-plugin-file.git
Uh oh!
"/Users/administrator/app-builder/STAGING/client/modules/AGCordova/src/org/apache/cordova/file/EncodingException.java" already exists!`

**Comment by harsaharsa** [comment]
`cordova-plugin-file`, along with many of the other core plugins is included by default with AppGyver Wrapper. We hadn't ran into the `<dependency>` tag before and thus the Build Service doesn't account for it. I created an issue for this: https://github.com/AppGyver/steroids/issues/993

For your case, forking the plugin and removing line 9: https://github.com/MobileChromeApps/cordova-plugin-zip/blob/master/plugin.xml#L9 will cause the plugin to install correctly.
