### ISSUE TITLE
Android and supersonic.ui.drawers.init

### ISSUE THREAD

**Issue by andybbtt11** [AppGyver/steroids#987]
In an attempt to achieve full viewport width drawers, I have tried to preload the drawer's html in structure.coffee, and initialize the drawer in another controller where the width of the view is the width of the device. 

The following code works flawlessly on iOS:

----[structure.coffee] ----

preloads: [
    {
      id: "leftDrawer"
      location: "common#drawer"
    }
]

----[HomeController.js]----

var deviceWidth = window.innerWidth;
var options = {
	side: 'left',
	width: deviceWidth
};

supersonic.ui.views.find("leftDrawer").then( function(leftDrawer) {
	supersonic.ui.drawers.init(leftDrawer, options);
});

This code in Android, however returns the following error:

supersonic.logger.error: supersonic.ui.drawers.init rejected: {} supersonic.js:28872
Unhandled rejection Error: Android does not support enabling drawers on runtime.

Is getting a viewport width drawer on any device not possible with the Android platform?
Or perhaps this documentation should get an iOS Only flag: http://docs.appgyver.com/supersonic/api-reference/stable/supersonic/ui/drawers/init/

**Comment by satusuuronen** [comment]
Please see [#749](https://github.com/AppGyver/steroids/issues/749). I am closing this issue.
