### ISSUE TITLE
Views are not preloaded if tab bar is missing

### ISSUE THREAD

**Issue by clarif** [AppGyver/steroids#988]
This is a copy/paste of a [message posted yesterday](http://community.appgyver.com/t/cant-preload-views/4923) of the AppGyver forum, as I believe it is not working as expected: views are not preloaded when no tab bar is defined in the structure.coffee file. 

Structure.coffee file:

```coffeescript
preloads: [
  {
    id: "abc-index"
    location: "abc#index"
  }
]
```
Then a link to the view-id defined above throws a 404 error (e.g. "Cannot GET /abc-index").

```html
<super-navigate view-id="abc-index">
  <button class="button button-energized button-block">
    test
  </button>
</super-navigate>
```

I also tried to preload views programmatically with the syntax shown below, but it failed as well:

```javascript
view = new steroids.views.WebView({location: "...", id: "..."});
view.preload();
````
Tested from the scanner app (both on the iOS simulator and an iPhone) with steroids.js v3.5.11 and 3.5.12.

But, if tabbar is added as shown below (and hidden with `supersonic.ui.tabs.hide();`  because I don't need it), all views defined in the preload section are effectively preloaded.

```coffeescript
  tabs: [
    {
      title: "Index"
      id: "index"
      location: "session#login"
    }
  ]
````

**Comment by harsaharsa** [comment]
Preloads do work without the tab bar on both iOS and Android, just verified with latest versions. Are you sure there's no syntax error? Are you defining the `rootView` object (required if no tabs are defined)? 

If you have a full Supersonic repro project that has this issue, please post it here and I'll reopen the issue.

**Comment by clarif** [comment]
Thanks. Indeed it works with the rootView object defined.
