### ISSUE TITLE
Application Loader throws error saying required icons aren't present even though they are.

### ISSUE THREAD

**Issue by gokulnathsridhar** [AppGyver/steroids#989]
Hi, I'm trying to uploading an App Store build to iTunes Connect via the Application Loader using Build 4.0.3, and I get the following error.
![apploader](https://cloud.githubusercontent.com/assets/2370127/8632931/cdafc9a4-27ce-11e5-8cb8-70618e301ea0.png)
I unzipped the application and checked for the assets that the Application Loader reported missing; they seem to be in tact, and the dimensions are right, as well.
![folder](https://cloud.githubusercontent.com/assets/2370127/8632943/4db82e66-27cf-11e5-80fb-f7af9f4e15e3.png)
Could you guys help me solve this issue? It's pretty urgent.

**Comment by Leeds-eBooks** [comment]
Have you tried re-uploading all the assets to the build service and building again?

**Comment by gokulnathsridhar** [comment]
Hi Leeds, yes I did. I even created new ones and uploading them. Didn't work.

**Comment by harsaharsa** [comment]
What's your Application ID? We'll check things on our end.

**Comment by gokulnathsridhar** [comment]
Hi Harsa, truly sorry for the late reply; I *recreated* the assets and uploaded. It worked. Thanks a lot for the response, though. :)
