### ISSUE TITLE
Make .dsym files available via the Build Service so crash reports can be symbolicated

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#990]
Currently, the .dsym file created when building an app via the Build Service is not available for download. This means that crash reports from a physical device (or App Store reviewers) are not much use. Make the .dsym file of each build available for download from the Build Service.

**Comment by harsaharsa** [comment]
`.dSYM` files are now available on request for iOS builds. Drop a mail to contact@appgyver.com with your build and app ID and we'll hook you up.

Keeping this issue open until it's available via the UI!

**Comment by satusuuronen** [comment]
dSYM files for all iOS builds are now available to download from the "Build History" menu in the Build Service.
